### ISSUE TITLE
ORM cuts off UTF-8 characters on INSERT

### ISSUE THREAD

**Issue by tom-phpgenie** [fuel/orm#100]
I’ve got a password heavily encrypted and it often features UTF-8 characters.

Here’s an example query:

```
INSERT INTO `users` (`email`, `password`) VALUES ('test@example.com', '5615642dSMl„ Þª;/Â\\ðÞtç©æíXŽU<—¡»“I@\":…l[úJ„8PùJ.‰#\\Ê–ˆh£e[3á');
```

If I `var_dump()` the object before and after `save()` it will correctly store the password. However, when I look at the database, only `5615642dSMl„` appears, then nothing else in the password field.

If I take the query and run it through MySQL via the command line or phpMyAdmin, it works.

Somebody mentioned that `utf8_decode` or `utf8_encode` might be to blame, but I can’t find any reference to them in the source.

Tried using 1.0 and 1.1-dev.

**Comment by frankdejonge** [comment]
What is your field charset?

**Comment by tom-phpgenie** [comment]
I’ve just run the same thing through the DB class with the same problem. Problem with the Core then?

**Comment by tom-phpgenie** [comment]
Database: utf8_unicode_ci
Table: utf8_unicode_ci
Fields: utf8_unicode_ci

**Comment by frankdejonge** [comment]
I can't reproduce this error. Did you check your field restraint? Works fine here with the exact same value.

**Comment by tom-phpgenie** [comment]
Field restraint is 255. It works fine when you run the query from the command line or through something like phpMyAdmin, always fails through Fuel. Where it gets cut off changes too, it’s always at the first UTF-8 character. I’ll try debugging some more... Might be MAMP related, normally is.

**Comment by frankdejonge** [comment]
As you can see here nothing strange here. http://d.pr/MZ2v I'm working on MAMP too (2.0.3).

**Comment by tom-phpgenie** [comment]
Grrr, this is going to drive me up the wall I can tell. Thanks for your help anyway @FrenkyNet !
