### ISSUE TITLE
\Orm\ValidationFailed would be really great if it contained the validation instance

### ISSUE THREAD

**Issue by phil-lavin** [fuel/orm#101]
It was a great change to include the string output of errors from the validation in the message of the exception. Would it be worth my while adding a reference to the whole Validation instance to this exception also? It'd be really useful, especially with Orm validation, to be able to obtain this without having to obtain a fieldset instance of the same name as the model the validation was run on.

If you think this is worthwhile, I'll submit a patch.

**Comment by jschreuder** [comment]
That could be usefull, though reference the fieldset and not the validation (you can get the validation from the fieldset).

**Comment by phil-lavin** [comment]
Ok, will do on Monday. Thanks :)
