### ISSUE TITLE
Soft Delete/Archive Row

### ISSUE THREAD

**Issue by jesseobrien** [fuel/orm#105]
I'm thinking it might be beneficial to include a soft-delete feature that uses a `deleted_at` field in the database to allow a row to be referenced as "deleted", but not removed from the database. I work in the medical field where we aren't ever allowed to actually delete data from a database, so this would be handy. I have some code roughly laid out, but I'd need some help figuring out how to get queries to use it as a filter.

**Comment by jesseobrien** [comment]
I forked and created some of the code to support a primitive soft delete to be set in the model by
`protected static $_soft_delete = true;`

Check the notes on this commit for rough @todo list.
https://github.com/JesseObrien/orm/commit/3214792f07216c9d5c033723cee27da0de00829d#commitcomment-657592

**Comment by jschreuder** [comment]
My feeling is that this is more something for an extension than as actual part of the core Orm.

That's not to say that it's no good btw, WanWizard's awesome [NestedSets extension](https://github.com/WanWizard/fuel-nestedsets) is an example of something like that.

**Comment by jesseobrien** [comment]
Thanks. How would I go about providing an extension?

**Comment by jschreuder** [comment]
Take a look at the example. You put it in a package and put the repo on Github. If you @fuel-packages it can be forked into that account to make it installable through Oil and soon when we release Fuel Cells you can register your package there so it won't need forking.

**Comment by jesseobrien** [comment]
Awesome! Thanks a lot.

**Comment by rclanan** [comment]
I actually think this is a very handy feature to have if wanting to compete in the business world. If this can be accomplished easily as an extension then that's cool. Otherwise I don't see the harm of it being in the core since it would be a very logical feature that will be used by a lot of people and it's configurable so not "forcing" people into using it. Just my opinion, I was going to try and do this with an observer or something somehow but haven't got that far into the ORM yet. Glad someone else ran into this before I got to it!

**Comment by jschreuder** [comment]
Something both of you should realize: being able to edit something is just a little bit less destructive than being able to delete (emptying out a row isn't that different from deleting it). If you want to make sure nothing gets truly deleted the solution isn't any kind of soft-delete but instead to keep track of all changes made to the database, be they deletion or edits. I've implemented this in my own app by generating a diff of each edit/deletion and logging it in a table keeping track of DB updates.

A "soft-delete" as proposed here has many potential problems: How to deal with relations? (will they be broken? do they need to keep existing just as much as the original object? how to deal with a to-one relation of which the other end is soft-deleted?) How to prevent fetches to include the soft-deleted items? How to prevent relations from including soft-deleted items? Once you start doing those things automated you run the risk of changing the query more profoundly than you first realized, resulting in far worse data-integrety problems than a deleted entry.

Any soft-delete like this isn't really a solution to prevent data-loss, it's a stop-gap with massive holes in it.

There are situations in which I do see use for soft-delete like behavior. For example when one of my SaaS-clients terminates their subscription I don't delete them but I give them the status deleted and have them removed from all normal listings. I do however consider any such behavior to be app specific, very much not generic.

**Comment by jesseobrien** [comment]
I agree with your sentiments on the potential problems. This discussion is good. My thoughts on this feature are stemming from my own experience with a lot of the apps that I build only offering database access through the app front-ends, with highly restricted access to the raw db via straight mysql or phpmyadmin access. This gives me complete (unless someone goes rogue) control over how I handle the "data-loss" aspects you mentioned. The obvious data-backup rules apply to real data-loss scenarios such as don't give idiots physical access, back-up your database properly, etc. This solution is more of a safeguard for auditing and checking past records than any real attempt at thwarting the data being truely lost. For some reason auditors love it when you can dump a 10,000 row query of rows that have been nicely archived and marked deleted among the active rows.

In regards to modifying querys, I'm not sure of the scope of that yet. All of your points are exactly what I need to think through and get ironed out, the idea is still very immature. I haven't learned enough about how Fuel puts together its querying to see what I can do with the code. I think cascading\* and fetching*\* data would be easy enough to deal with, but you're right about the to-many relationships being quite muddy water. I'll have to explore it more.
- Cascades should be fairly simple to head down through with both soft_delete() and restore() by following relations and having the cascade switch available to the user.

*\* Putting a default filter on every fetch query that includes `WHERE 'deleted_at' == NULL` which can be overridden by a chained method ->include_deleted() or that sort of syntax seems like an intuitive way to go about it. 'deleted_at' can be defined by the user.

**Comment by emlynwest** [comment]
I know this is an old issue and is now closed but I have been working on a version of the orm that handles soft deleting. It's based on 1.4/develop and can be dropped into any current project that uses orm without breaking anything. It's possible to define cascade-soft-deletable models but both models in a relation need to soft deletable if cascade delete is true.

There is still some work to do (like many-to-many and hard deleting soft deletable models) but if there are any ideas/questions then feel free to start an issue on my repo. There is no documentation (yet) so please feel free to ask and I will do my best to reply quickly. (Again, don't ask here but over at my repo linked below).

I post this here in the hope that others needing this functionality will have another place to look. 

https://github.com/stevewest/orm
