### ISSUE TITLE
A bug which occurs when trying to validate and save related models

### ISSUE THREAD

**Issue by kapv89** [fuel/orm#110]
suppose Model_A has_many Model_B ... if i do  $a=new Model_A ... $b = new Model_B ... $a->b = $b... $a->save() .. now if validation fails only for $b, $a is still saved

**Comment by jschreuder** [comment]
This isn't a bug, it's a consequence of how events proceed. For has-many the parent object is saved before the belong-to kids are saved (they need the parent's ID). To provide a solution for this I recently added support for DB transactions to the ORM, this will do a full rollback if it fails along the way.

They were tested on InnoDB mySQL databases, but there are more DBs that support it (MyISAM mySQL doesn't).
