### ISSUE TITLE
Add before_find and after_find event calls to the find function. Idea from Model_crud pre_find and post_find functions.

### ISSUE THREAD

**Issue by rclanan** [fuel/orm#113]
Reference links:

https://github.com/fuel/core/blob/1.1/develop/classes/model/crud.php#L197
https://github.com/fuel/core/blob/1.1/develop/classes/model/crud.php#L202

I would like to propose that before_find and after_find be added to the find function. A non-working example can be found at https://github.com/fuel/orm/pull/112 to give an idea of what I was referring to exactly. 

Thanks..

**Comment by jschreuder** [comment]
In the ORM events are observed upon the instances of the model class, this makes any kind of `before_find` event impossible as there are no objects yet to observe.

The `after_find` event already exists: `after_load`.
