### ISSUE TITLE
Only first related row is available in object 

### ISSUE THREAD

**Issue by jfhs** [fuel/orm#116]
In Query->get function, for each returned row hydrate function is called. This function sets related data only if it hasn't been set yet

Lines 824-833 packages\orm\classes\query.php

```
        // when not yet set, create the relation result var with null or array
        if ( ! array_key_exists($m['rel_name'], $rel_objs))
        {
            $updated_relations[] = $m['rel_name'];
            $rel_objs[$m['rel_name']] = $m['relation']->singular ? null : array();
        }

        // Only hydrate when relations weren't already fetched
        if (in_array($m['rel_name'], $updated_relations))
        {
```

So when relation is not yet there it fetches data from row sets it as updated and next rows are not processed.

**Comment by jschreuder** [comment]
It's a known bug in the 1.1-RC, fixed in the develop branch.

**Comment by todd1251** [comment]
Should someone else have this problem with 1.1-RC1, you can grab the latest version from the develop branch:
https://raw.github.com/fuel/orm/1.1/develop/classes/query.php

So far just patching that seems to have resolved the issue for me without any side effects... yet :-)
