### ISSUE TITLE
Saving a Model with (non-populated) Relations throws an Orm\FrozenObject Exception

### ISSUE THREAD

**Issue by andrewwheal** [fuel/orm#117]
Changes have been made to `Orm\Model::is_changed()` whereby it tries to populate a models relations when that model is saved (this seems to be triggered when `Orm\Model::$_original_relations` is accessed).

As it is a save the `Orm\Model` object is frozen, meaning that when `Orm\Query::hydrate()` calls `Orm\Model::_relate()` the latter's  `if ($this->_frozen)` check throws an `Orm\FrozenObject` exception.

If the elseif and else here - https://github.com/fuel/orm/blob/1.1/develop/classes/model.php#L1248 - are commented out then everything seems to work fine.

IMO, loading all of the relations on a model when it is saved is a bad idea, as the model being saved could have several has_many or many_many relations which have not been populated for the reason that they could be huge and use a lot of memory when loaded.

**Comment by jschreuder** [comment]
Looking at it now there are a few mistakes in there indeed: relations shouldn't be checked using `$this->{$p}` as that triggers the lazy load - `$_original_relations` doesn't. Also `empty($this->{$p}` shouldn't work as it depends on `__get()` and empty() has problems with that.

I'll upload a fix without closing the issue, can you check it? (in about 10 minutes)

**Comment by andrewwheal** [comment]
Sorry I haven't checked this sooner.

I am now getting a OutOfBoundsException for relations that have not been loaded prior to the save() call.

This was tested by creating a new Model_Vacancy and populating a has_many Model_Question relationship, the OutOfBoundsException is on the relation going back

```
object(OutOfBoundsException)[117]
  protected 'message' => string 'Unknown property or relation: vacancy' (length=37)
  private 'string' (Exception) => string '' (length=0)
  protected 'code' => int 0
  protected 'file' => string '/mnt/pdrive/Clients/youngsrecruitment/versions/whealer/includes/fuel/packages/orm/classes/model.php' (length=99)
  protected 'line' => int 1278
```

**Comment by jschreuder** [comment]
Ahh, don't understand why I'm not getting this but I get why it happens.

**Comment by andrewwheal** [comment]
Rerunning my initial test works so looks like this could have done the job.

Will test a little further just to make sure.

**Comment by peter-fritchley** [comment]
This seems fine when saving new models, thanks.

**Comment by jschreuder** [comment]
Thanks for the verifications, closing this now - will reopen if something turns up.
