### ISSUE TITLE
Possible LIMIT issue with (has many) related entities

### ISSUE THREAD

**Issue by bunchjesse** [fuel/orm#118]
The following code is not performing as I would expect:

```
$myPost = static::query()->related('comments')->get_one();
```

My expectation is that this would return the first `post` object but return all related `comments`. In fact, this bit of code worked perfectly prior to upgrading to v1.1 RC1. 

Instead, this code is returning the first `post` object and only one `comment` object. I didn't see anything in the change log about this. Perhaps it's a bug or am I doing something wrong?

**Update 1**

Looks like the query that's generated is fine. When run manually, it returns the correct number of comments. This makes me think the issue might lie in the hydration routine. Hrmm....

**Comment by jschreuder** [comment]
It's a bug in RC1, fixed in develop branch
