### ISSUE TITLE
\Orm\Query create duplicate order_by statement.

### ISSUE THREAD

**Issue by crynobone** [fuel/orm#120]
There a bug with the current Orm package for FuelPHP, seem to me the order_by was added twice.
## Reference:
- https://github.com/fuel/orm/blob/1.1/develop/classes/query.php#L614
- https://github.com/fuel/orm/blob/1.1/develop/classes/query.php#L765
## Example Code:

```

\Model_Work::query()
    ->order_by('to', 'ASC')
    ->order_by('from', 'DESC')
    ->get();

# Generate
SELECT ...
FROM `works` AS `t0` 
ORDER BY `t0`.`to` ASC, `t0`.`from` DESC, 
`t0`.`to` ASC, `t0`.`from` DESC
```

**Comment by WanWizard** [comment]
Issue was fixed and merged months ago. Closing issue.
