### ISSUE TITLE
Possible undefined index in Observer_Slug

### ISSUE THREAD

**Issue by tabacco** [fuel/orm#127]
In the expression on line 61, the only match is optional, so preg_match() can return 1 and cause execution to enter the if statement even if there's no index trailing the slug.

If this happens, $matches[1] isn't set on line 64, triggering an E_NOTICE.

My cheap fix is to replace line 64 with `$index = isset($matches[1]) ? (int)$matches[1] : 0;`

**Comment by billmn** [comment]
I've fixed this with a pull request

**Comment by dmyers** [comment]
Ran into this too. Hope they merge this. I found this thread first:
http://fuelphp.com/forums/topics/view/6408

**Comment by HellPat** [comment]
With this fix the oberserver works fine!

**Comment by jschreuder** [comment]
@billmn you didn't actually pull-request did you? The commit is shown here but I can't pull it using Github right now.

**Comment by billmn** [comment]
I've pulled a request here: https://github.com/fuel/orm/pull/144
Observer_Slug fix was appended into "Fixed label translation in validation messages (Fixed Issue #130)" ... what can I do?

**Comment by jschreuder** [comment]
I just noticed, for once it's not a problem as both will be accepted.

**Comment by jschreuder** [comment]
Solved by https://github.com/fuel/orm/pull/144
