### ISSUE TITLE
Bytes exhausted with to_array()

### ISSUE THREAD

**Issue by billmn** [fuel/orm#129]
Hi, I'm not sure if this is a bug but I think you can check if this can be.

I'm using 2 small tables :
- Users (that contains 2 records)
- Groups (that contains 3 records)

During some ORM tests I've tried :

<pre>
$group = Model_Groups::find('first', array('related' => array('users')));
$user  = Model_Users::find('first', array('related' => array('group')));

\Debug::dump($group, $user);
</pre>

And all works fine, but with :

<pre>
$group = Model_Groups::find('first', array('related' => array('users')))->to_array();
$user  = Model_Users::find('first', array('related' => array('group')))->to_array();

\Debug::dump($group, $user);

Fatal error: Allowed memory size of 33554432 bytes exhausted (tried to allocate 81 bytes) in .../fuel/packages/orm/classes/model.php on line 1533
</pre>

This is the relations added to models

<pre>
// Groups
// ------------------------------------------------------
protected static $_has_many = array(
    'users' => array(
        'key_from'       => 'group_id',
        'model_to'       => 'Model_Users',
        'key_to'         => 'user_group_id',
        'cascade_save'   => false,
        'cascade_delete' => false,
    )
);

// Users
// ------------------------------------------------------
protected static $_belongs_to = array(
    'group' => array(
        'key_from'       => 'user_group_id',
        'model_to'       => 'Model_Groups',
        'key_to'         => 'group_id',
        'cascade_save'   => false,
        'cascade_delete' => false,
    )
);
</pre>

Cheers

**Comment by jschreuder** [comment]
The method needs a circular reference detection, the only way to do that is probably to pass an array around while it's being executed that keeps tack of which objects have already been array'd

**Comment by andrewwheal** [comment]
This seems to me like a pretty big bug but still exists. Is there any chance of getting it fixed?

**Comment by WanWizard** [comment]
This will stop the error. 

But ideally you would like to solve circular references by adding a self-reference to the result. But for that the method needs to keep a link to all objects so it can add those references, which is complex, and memory and time consuming. Not sure if that is really needed.

**Comment by WanWizard** [comment]
@SicoAnimal is further action needed here?

**Comment by WanWizard** [comment]
Closed due to no response.
