### ISSUE TITLE
[Feature] Label an Relation

### ISSUE THREAD

**Issue by dbpolito** [fuel/orm#133]
Would be great if there is a way to label the rellation, something like:

protected static $_has_many = array('comments' => array(
    'table' => 'table_name',
    'model_to' => 'Model_Fancy_Comment',
    'key_from' => 'article_id',
    'key_to' => 'parent_article_id',
    'cascade_save' => true,
    'cascade_delete' => false,
    // there are some more options for specific relation types
));

It's also good when we need to do 2 relations to same table but different key_from, for example: a table that has user_id_from and user_id_to or something like that.

**Comment by WanWizard** [comment]
What exactly is the point of adding the table name in this definition?
The model defines the tablename, so it's pointless defining it here.

And as far as I know, this is not a problem too:

```
protected static $_has_many = array(
    'comments' => array(
        'model_to' => 'Model_Fancy_Comment',
        'key_from' => 'article_id',
        'key_to' => 'parent_article_id',
    ),
    'otherrel' => array(
        'model_to' => 'Model_Fancy_Comment',
        'key_from' => 'article_id',
        'key_to' => 'parent_other_id',
    )
);
```

**Comment by jschreuder** [comment]
This seems to be only about adding the table name, which won't happen as the table name should be specified inside the model.

Defining different relations to the same model using different properties as foreign key is already possible as @WanWizard pointed out.

**Comment by dbpolito** [comment]
Sorry, my bad... Thanks for your assistance.
