### ISSUE TITLE
Too many fields mentioned during insert

### ISSUE THREAD

**Issue by philsturgeon** [fuel/orm#143]
When I try to set JUST one field and run save() it sets every other field in the insert to null. That initially seems sensible, until you want one of those fields to be not null, but default to 0.

The database should be able to deal with that, but because we are explicitly sending in nulls from the ORM it throws an error: 

```
Fuel\Core\Database_Exception [ Error ]: SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'referral_count' cannot be null with query: "INSERT INTO `subscribers` (`email`, `referral_code`, `referral_count`, `click_count`, `referrer_id`, `created_at`, `updated_at`) VALUES ('foo@bar2.com\r', null, null, null, null, 1331649076, 1331649076)"
```

http://d.pr/fM6W

Really, only email should be mentioned in this insert, along with anything set by hooks (created/updated). Everything else needs to be ignored entirely so the database can do its thing.

I can of course for now get around this by hardcoding `$model->foo = 0;` for each of the fields, but I should not need to do that.

**Comment by jschreuder** [comment]
The object should know what it contains during runtime or you'd never be able to use it after creating it without a select directly after insert. Thus it needs all defaults set and sets them to `null` if you haven't.

Conceptually any ORM should work like this: it creates an object during runtime and it saves that exact object to the database for later retrieval. How it is saved or what it looks like when saved shouldn't be things the ORM concerns itself with other than being able to translate it back and forth between runtime and the DB. But the DB setting values should not be part of it.

You may argue with it but the only way this is ever going to change is if you find someone to take maintenance and development from me, as I won't do anything but bugfix it from this point on as I've stated.

**Comment by philsturgeon** [comment]
Ok. I found default => 0 in the $_properties list. It's not ideal, but it works. 

## 

Phil Sturgeon
