### ISSUE TITLE
Identity map (cached_object()) doesn't respect selected columns

### ISSUE THREAD

**Issue by axelarge** [fuel/orm#146]
When selecting an object from the db, it gets cached inside the ORM class, so selecting it again will not issue an additional query.

However the cache ignores the fact that the result from the first select might be incomplete. Here's an example:

``` php
Model_Folder::find($id, array('select' => 'id'));
$folder = Model_Folder::find($id);
// Now $folder has no properties except $id !
```

The identity map should check if subsequent selects select columns that are missing in the cached object and fetch it again if needed.

**Comment by jschreuder** [comment]
This is a known limitation, the select() method was initially never meant to be used publicly and no one has ever taken the time to add real support for it. I'll leave it open for anyone to look into this.

**Comment by WanWizard** [comment]
This solved the issue in this case:

``` php
Model_Folder::find(array('select' => 'id'))->get();
Model_Folder::find(array('select' => 'name'))->get();
```

It does not fix the problem when running a find() on PK, as that would not run a query at all, so it has no notion of what has or has not been selected. 

Perhaps it's an option to retrieve it from the cache, check against the properties if all columns are present, and if not, ignore the cached value?

**Comment by WanWizard** [comment]
As a workaround, from_cache() can be used to run a new query ignoring what is already in cache.
