### ISSUE TITLE
ORM loses the first nested relation it updates

### ISSUE THREAD

**Issue by quetzyg** [fuel/orm#154]
First, here is my simplified model hierarchy:
Model_Teacher (has_many)-> Model_Schedule (many_many)-> Model_Student

As the title implies, when updating an existing Schedule, the relation between Schedules and Students gets lost.

Here is a Debug::dump() of the $teacher object before running $teacher->save(true, true);
http://scrp.at/bpt

From the object dump, we can see that the relations between Teachers and Schedules exist, as well as the relations between Schedules and Students.

On the final lines, where the resulting queries are, the transaction should have an update on the schedules_students table, but it doesn't.

This _only_ happens on the _first_ tuple that gets updated. If I update several Schedules, only the first will loose the relations with Students. The remaining, will have all the relations as expected.

Feel free to ask for more info if needed.

Edit: some typos and better explained myself.

**Comment by quetzyg** [comment]
I've pulled the latest ORM package and looks like one of the three last commits solved this issue.

**Comment by WanWizard** [comment]
Can you confirm that so this issue can be closed?

**Comment by quetzyg** [comment]
Yes, it can be closed :)
