### ISSUE TITLE
Relations are not fetched for new objects

### ISSUE THREAD

**Issue by Savageman** [fuel/orm#171]
It's basically all explained in this ScrapYrd: http://scrp.at/buD#L47

A new item won't try to fetch a relation. I'm wondering why it is that way?

In the example, I create a new object, set a property so the relation can properly be found if I request for it. But it's not fetch since it's a new item. Seems a bit strange to me.
I'm not sure whether it's intended or not, that's why I'm asking!

Thanks.

**Comment by WanWizard** [comment]
A new item can never have a relation, you can't relate to something that does not exist yet.

It would be possible to fetch them for relations where you have the FK, but not in all other cases as a new object doesn't have a primary key yet.

**Comment by Savageman** [comment]
A `belongs_to` relationship needs only a FK to exists, the PK is not necessary. Maybe I didn't insist much on this in my example. `belongs_to` feels like a special case maybe. It should at least try to get the remote model.
I agree nothing can be fetched for other relation types though (as they a need a PK to fetch the data).

I was thinking the logic of checking whether it's a new object or not should be in the `get()` methods within the relations, as the need of the PK depends on the type of relation we have?

**Comment by WanWizard** [comment]
That's what I wrote, if you have a valid FK then you should be able to fetch them.

The relationship definition should tell you if the FK is in the current or in the other model.
