### ISSUE TITLE
Access properties of pivot table in many-many relations

### ISSUE THREAD

**Issue by peter-fritchley** [fuel/orm#175]
It would be helpful to be able to access things form the pivot table, a typical use case is with products and categories. A product can belong to many categories and a category may have many products, but also the product has a specific position in the category.

**Comment by WanWizard** [comment]
Any suggestion on how to implement that?

As I see it a many-to-many is really a set of one-to-many relations with a through table model in the middle. You will need some way to access that model. Using a property would be a consistent solution, but requires to you define the name of the property in the relation definition.

**Comment by peter-fritchley** [comment]
If you put it in the relations array of the related model, then you wouldn't have to define the name of the property. Then you could access it like any other relation of that class e.g in the category product example: $category->products[$i]->pivot->order

This would break if product had a relation named 'pivot' already, but perhaps you could change that on the model itself, similarly to how you tell it to use a different primary key.

**Comment by WanWizard** [comment]
That's why I referred to "the property", instead of "pivot". You need to be able to define it (like you can do the relation name) to avoid collisions (and to use a for-you practical name, I would have never thought of the word "pivot").

**Comment by WanWizard** [comment]
Looked at this, but this is very complicated to implement, and it doesn't add much extra to the current solution, which is to split the relation into two one-to-many relations using a 'pivot' model in the middle:

``` php
// get the order number in the pivot table
$category->pivot[$i]->order;

// get the product related to this pivot record
$category->pivot[$i]->product;
```
