### ISSUE TITLE
ArrayAccess implementation makes use of __get and __set

### ISSUE THREAD

**Issue by peter-fritchley** [fuel/orm#176]
This means that only properties retrieved from the database can be retrieved from the model using the Arr class. It would be desirable for the ArrayAccess implementation to take into account other properties on the model, to allow consistent data retrieval using the Arr class.

**Comment by WanWizard** [comment]
What other properties are you talking about? In general ORM object should not contain other data then the data related to the fields in $_properties.

**Comment by peter-fritchley** [comment]
I disagree, ORM models are used as more than just data access objects. For example on a product model, you might have a $taxed_price property which is generated at the point the product is loaded. This cannot be stored in the database as it is the result of some calculation.

**Comment by WanWizard** [comment]
To implement this properly it needs to use some sort of container for these properties. If you allow access to normal class properties like this, all internal properties suddenly become accessable.

Which means you must use something like

```
protected $_other_properties = array('taxed_price' => 0);
```

set() and get() need to be changed to look in this container too for consistent behaviour. Which automatically gives ArrayAccess access to these properties too.
