### ISSUE TITLE
FrozenObject exception a bit cryptic

### ISSUE THREAD

**Issue by Altreus** [fuel/orm#177]
The FrozenObject exception crops up every now and then, and with a bit of help from the community one can often determine the cause and, eventually, come to understand the freezing mechanic.

It would be helpful to have some documentation on the whole concept of freezing, and perhaps some common cases in which the object can become frozen without the user realising, in order to avoid it, or to diagnose it when it happens.

**Comment by jschreuder** [comment]
Something like on the bottom of [this page](http://docs.fuelphp.com/packages/orm/intro.html)?

**Comment by Altreus** [comment]
Yah, but I was thinking a more in-depth description. I still don't feel like I understand the concept and I've come a cropper of it several times.

**Comment by WanWizard** [comment]
I've been thinking about this, but I can't come up with a better explaination then the one already in the docs.

You can get this exception, as the text explains, if you have an issue with your relationship definitions, or if you have circular relations ( users -has-many- groups -has-many- users -has-many- ... ) and use cascading.
