### ISSUE TITLE
Return collections of models as an iterable class rather than an array

### ISSUE THREAD

**Issue by peter-fritchley** [fuel/orm#179]
This would allow passing around a query, which would get executed at the point at which someone tries to iterate it. This approach would give greater flexibility - since at each level of processing, further conditions / relations could be added. It would also remove the need for \Orm\Query::get().

**Comment by WanWizard** [comment]
I understand (and like) the idea. 

But it would not remove the get(), as that is actually the SQL execution trigger which would create the iterable class. You will have to create and populate it before you can access it's data.

**Comment by peter-fritchley** [comment]
I thought that the class could keep track of whether the internal store of models had been generated, and trigger the SQL on the first iteration (or the first iteration after new conditions have been added). Then you don't need to care about whether the data has been fetched yet or not.

**Comment by WanWizard** [comment]
Ok, but you would still need the get() for all other scenario's (in which you want to access the object without iteration).

**Comment by AddoSolutions** [comment]
I have posted a solution to this here:

See my original thread here: https://github.com/fuel/orm/issues/249

and the pull request #270

**Comment by WanWizard** [comment]
Continue the discussion in that thread.
