### ISSUE TITLE
Have to_array() work like in the DB class

### ISSUE THREAD

**Issue by jeffutter** [fuel/orm#18]
Issue edited by Jelmer:
This relates to issue #17 and can be closed but for the suggestion to make to_array() work like as_array in the DB class: https://github.com/fuel/core/blob/master/classes/database/result.php#L92
End edit.

It may be wise to blacklist certain fields from toArray or hydration unless specifically requested for. I realized this when I noticed my REST controller which returns a chat message model object and the related user object contained the users password hash. I realize this can be fixed with an unset call in the controller but I think it would be wise to be safe rather than sorry in situations where private data may be exposed (password hashes, credit card numbers, etc.)

**Comment by jschreuder** [comment]
This may be implemented with to_array() by having it accept an array of values that are the only ones returned (or removing some by using `array('field' => false)`).
Another way this could be implemented would be by creating a post-to_array event which gets passed the new array to allow you to change it with an observer before it's output.

But as discussed on IRC: hydration will never ignore anything that was fetched from the DB, that's just dumb & wastefull - if you're going to ignore a value during hydration it shouldn't have been fetched in the first place. (Relates to issue #17)

**Comment by jschreuder** [comment]
Thought longer about this and decided to nix the whole idea. Doesn't really do much usefull, and when selecting only specific fields is possible in the next version this won't be necessary anymore.
