### ISSUE TITLE
Model doesn't fetch related models, if same Model is called before

### ISSUE THREAD

**Issue by MacTwister** [fuel/orm#180]
I don't know how to explain this.

But I'm having inconsistencies when running multiple Model fetches next to each other (even to the same model).

This issue started when I had a REST API, in which i fetch all products (model) and related models in an 'sequence' order. If i run this API in the browser i get all data in the right order..... However when i ran this API using `\Request::forge('fetch/categoryproducts)->execute()->response()` in a Task. The right data is there but no order to teh 'sequence' column.

So to try and figure this issue out, I preformed some test in a new Task. I realized strange behavior which i can't explain.

I have a few Models with a few relations with each other. (all seem find as it works perfectly around the CMS and in the browser with the API.

If I run in the TASK:
    `$Category = \Model_Category::find(22);`
I get my model data (no related data), good.

If after this I run:
   `$Category = \Model_Category::find(22, array( 'related' => array( 'categoryproducts' ) ) );`
I don't get the related model data..... 

But if I comment out the first find query, I get my beautiful related data.

The thing is in my application the first model query is in my task, and the second query (which is actually a more completed related deep set) is in my API which I call in the TASK.

So running these two Model queries in the same execution, its like it ignores my seconds cause it already called the first.

Note: even if i call `$Category = \Model_Category::find('all');` before the complicated second query call, the result of the the second call is still with out related data...... So maybe I'm maybe be doing something wrong, but I'm at a dead end.

**Comment by WanWizard** [comment]
This is by design.

The ORM is modelled on the Datamapper pattern, which means it caches results, and will not run a query to get the same result twice.

In this example you get a record by primary key, without eager loading of relations. The second request loads the same record, which is fetched from cache, no query is run. You should still be able to access the related record though through lazy loading, just request $Category->categoryproducts and the ORM will run a query to get them.

**Comment by MacTwister** [comment]
Ok, But when i do the lazy loading call, `$Category->categoryproducts` it wont use the order_by setting that I had in the latest Model call (the difference with the second ORM call is 2 extra related models and a order_by). 

Is there a way to force it. As its an API which is looping and calling different things. And in the TASK, where i also call that API, its already calling that Model to find out stuff, unrelated to the API call i made in the Task.

But its good to know how the ORM works like that. So maybe i should re-design how i call everything?

**Comment by WanWizard** [comment]
The previous call was a different query, the model doesn't remember your query, only the objects that were fetched.
