### ISSUE TITLE
Reverse Relationship Problem

### ISSUE THREAD

**Issue by jamesarnold** [fuel/orm#183]
Please see http://scrp.at/bIp for my controller code, model code and DB structure.  The problem seems to lie in the first sub query; it orders by the PK in `ASC` order and then does`LIMIT 1`.  This means that it is never possible for the `WHERE` clause to be true.  

It works if I do the relationship the other way - 
`Model_Product_Family::query()->related('i18n')->where('i18n.slug', '=', $slug)->get();`

**Comment by WanWizard** [comment]
Related to #172.

You can now fix this by doing

``` php
$foo = Model_Product_Family_I18n::find_by_slug($slug, array(
    'related' => array(
        'family',
    ),
    'rows_limit' => 1,
));
```

so it does the limit on the outer query instead of on the subquery.
