### ISSUE TITLE
Error - Primary key cannot be changed. in PKGPATH/orm/classes/model.php on line 941

### ISSUE THREAD

**Issue by dercoder** [fuel/orm#184]
When i create a new Model and set a PK value, then i get this exception on save.

Example 1:
$data = array('id' => '1', 'name' => 'Test1');
$model = new \Model_Betradar_Tournament;
$model ->set($data);
$model ->save();

Example 2:
$data = array('id' => '1', 'name' => 'Test1');
$model = \Model_Betradar_Tournament::forge($data);
$model ->save();

Problem: \Orm\Model set again all properties on save/create function

So i fixed it on this line:

if (!$this->is_new() and in_array($property, static::primary_key()) and $this->{$property} !== null)
{
     throw new \FuelException('Primary key cannot be changed.');
}

**Comment by steadweb** [comment]
In "Example 2", don't use forge, use find() -

$model = \Model_Betradar_Tournament::find($data['id']); 

// edit all the things 
$model->name = "Test 2";

// performs an update instead 
$model->save();

**Comment by dercoder** [comment]
Yeah but i dont want to update this entry. I want to create a new one without using an auto increment primary key

**Comment by steadweb** [comment]
In your example you're using the same PK (1), hence the assumption of wanting to update. The model looks like a joiner table anyway, so you shouldn't need a primary key, and more likely 2 (or more) foreign keys, if this is the case.

What are you trying to do exactly?

**Comment by dercoder** [comment]
You didnt understand me. I tried to save a new entry in my database by example 1 and example 2. There is no database entry now by this key.

And i got this error just on Version 1.3. In Version 1.2 the example 1 and example 2 worked fine

The Problem: When i call the "save" methode, the model set again all properties and on the second "set" method i got this error.

File: fuel/packages/orm/classes/model.php

Method: save
Line: 975
Code: $return = $this->_is_new ? $this->create() : $this->update();

Method: create
Line: 1026
Code: $query->set($p, $this->{$p});

Here can you see that the create method set all properties again

$properties  = array_keys(static::properties());
foreach ($properties as $p)
{
    if ( ! (in_array($p, $primary_key) and is_null($this->{$p})))
    {
        $query->set($p, $this->{$p});
    }
}

But i set my properties already before i used the save method

Method: set
Line: 890

if (in_array($property, static::primary_key()) and $this->{$property} !== null)
{
    throw new \FuelException('Primary key cannot be changed.');
}

Sure the model throw this exception on the second "set" call because the PK property is not null anymore

**Comment by WanWizard** [comment]
A model object in "not new" state has a primary key which is the idenfier of that record, and should not be changed under any circumstance. So if you try to update the PK of such a record, you get an exception thrown. 

This is by design, so don't do that.

**Comment by dercoder** [comment]
But this Mode is in "NEW" state and i got still this error. I know that i can't change the PK on an existing model object
Example:
$data = array('id' => '1', 'name' => 'Test1');
$model = new \Model_Betradar_Tournament;
$model ->set($data);
$model ->save();

**Comment by kenjis** [comment]
@WanWizard This bug affects version 1.3. Cherry-pick, please.
