### ISSUE TITLE
missing table prefix in /Orm/Model->properties

### ISSUE THREAD

**Issue by awei01** [fuel/orm#189]
should properties function be this?
    public static function properties()
    {
        $class = get_called_class();

```
    // If already determined
    if (array_key_exists($class, static::$_properties_cached))
    {
        return static::$_properties_cached[$class];
    }

    // Try to grab the properties from the class...
    if (property_exists($class, '_properties'))
    {
        $properties = static::$_properties;
        foreach ($properties as $key => $p)
        {
            if (is_string($p))
            {
                unset($properties[$key]);
                $properties[$p] = array();
            }
        }
    }

    // ...if the above failed, run DB query to fetch properties
    if (empty($properties))
    {
        try
        {
```

/_---- start change ----_/
                $table = \DB::quote_table(static::table());
                $properties = \DB::list_columns($table, null, static::connection());
/*--- end change --- */
            }
            catch (\Exception $e)
            {
                throw new \FuelException('Listing columns failed, you have to set the model properties with a '.
                    'static $_properties setting in the model. Original exception: '.$e->getMessage());
            }
        }

**Comment by WanWizard** [comment]
That should not be fixed in the ORM, it should be fixed in the DB class, since this is true for every call to list_columns().
