### ISSUE TITLE
Allow model properties to be null by default when creating new instance

### ISSUE THREAD

**Issue by ziadoz** [fuel/orm#19]
It would be really useful if a models properties were, or could optionally, be declared as null by default when creating a new instance. 

For example it would nice to be able to populate a form using a models public properties (see below). As it stands a newly created model instance requires all it's attributes setting manually.

``` php
<?php
class Controller_Welcome extends Controller_Template
{
    public function action_input($id = null)
    {
        $article = Model_Article::find($id) OR new Model_Article;
        $this->template->content = View::factory('welcome/index', array('article' => $article));
    }
}
?>

<?php echo Form::open(); ?>
    <?php echo Form::input('title', $article->title);
   <?php // Lots more form fields here. ?>
<?php echo Form::close(); ?>
```

**Comment by jschreuder** [comment]
It is likely this will happen anyway, but I'm not sure how this would change anything in your case. It should already output `null` for any valid property that is not set: https://github.com/fuel/orm/blob/develop/classes/model.php#L618

**Comment by ziadoz** [comment]
I was running Fuel RC2 when I noticed this issue. 

Upgrading the ORM package to the latest dev commit fixes it as you pointed out.
