### ISSUE TITLE
Caching models support

### ISSUE THREAD

**Issue by noith** [fuel/orm#190]
Hi. I'd like to request a feature of caching orm object by default caching mechanism.

I thing caching should be separated into two layers.
1) Query caching. This layer contains primary keys of rows, that are taken by this query.
2) Object caching. This layer has contents of the model ond is accessible by primary key. 

As the result orm goes to query cache and gets primary keys and then to object cache. If object is old it refreshes it. If there are too many object, it seems better to execute the whole query and refresh all objects.

Thanks in advance.

**Comment by WanWizard** [comment]
The ORM has an object cache built-in, which is per-request, and can't be switched off.

As for query caching, we feel that this should not be part of the ORM package, if you want to cache query results, you can do so with the Class class in a few simple lines:

``` php
try
{
    // fetch the cached query data
    $result = \Cache::get('myidentifier');
}
catch (\CacheNotFoundException $e)
{
    // not found, fetch it from the DB, then cache it for 5 minutes
    $result = Model_This::find('all');
    \Cache::set('myidentifier', $result, 300);
}
```
