### ISSUE TITLE
Relationships + Deleting problem

### ISSUE THREAD

**Issue by abdel** [fuel/orm#2]
I have 2 models User  and Company. Company has many users and belongs to creator (1 user, delete = false). User belongs to company.

When I delete a user from the company, I get the error: Orm\FrozenObject [ Error ]: No changes allowed.

Also another problem with stationwagon, I have Articles and Category (Category has many articles. Article belongs to category).

When I delete an article, instead of removing the article it removes the category that the article belongs to which is kinda confusing.

I wasn't able to trace errors.

**Comment by jschreuder** [comment]
Solved.
