### ISSUE TITLE
find('first') adding LIMIT wrong part of query

### ISSUE THREAD

**Issue by DregondRahl** [fuel/orm#20]
Using find('first') it returns blank because of LIMIT added to the tags table query before the WHERE query

``` sql
FROM (SELECT `t0`.`tag_id`, `t0`.`tag_type`, `t0`.`tag_name`, `t0`.`tag_slug` FROM `mini_tags` AS `t0` ORDER BY `t0`.`tag_id` ASC LIMIT 1) AS `t0` LEFT JOIN `mini_lists` AS `t1` ON (`t0`.`tag_id` = `t1`.`list_id`) LEFT JOIN `mini_lists_music` AS `t2` ON (`t1`.`list_id` = `t2`.`list_id`) WHERE (`t0`.`tag_slug` = 'supernatural')
```

This is the alternate syntax query, which works correct. using get_one();

``` sql
FROM (SELECT `t0`.`tag_id`, `t0`.`tag_type`, `t0`.`tag_name`, `t0`.`tag_slug` FROM `mini_tags` AS `t0` WHERE `t0`.`tag_slug` = 'supernatural' LIMIT 1) AS `t0` LEFT JOIN `mini_lists` AS `t1` ON (`t0`.`tag_id` = `t1`.`list_id`) LEFT JOIN `mini_lists_music` AS `t2` ON (`t1`.`list_id` = `t2`.`list_id`)
```

There is another bug also with deep relations, but i'm trying to find the exact cause. In this situation i'm getting 'list' related (one-to-one) 'music' related (one-to-many) to 'tags', but when reversing to get tags from list the 'tags' end up empty. I will make a proper post regarding this once i figure out if its my mistake or an error.

**Comment by jschreuder** [comment]
Hmm, that's weird. Could you give the PHP code you've used to get both queries?

**Comment by DregondRahl** [comment]
``` php

        $view->content = Model_Tag::find('first', array(
                'where' => array('tag_slug' => 'supernatural'), 
                'related' => array(
                        'list' => array('related' => array('music'))
                )
        ));

```

``` php

        $view->content = Model_Tag::query()
            ->related('list')
            ->related('list.music')
            ->where('tag_slug', '=', 'supernatural')
            ->get_one();

```

**Comment by jschreuder** [comment]
The above will probably solve it for your problem. There are however still serious limitations to using limit and nested where conditions, which are even more obvious when using the first method of querying.

**Comment by DregondRahl** [comment]
This seems to be solved, thanks!
