### ISSUE TITLE
Query::count() does not consider use_view (SQL views)

### ISSUE THREAD

**Issue by keigoi** [fuel/orm#208]
Even if we call use_view(), count() does not return the sum of rows of the SQL view.
For example, the code below

``` php
$count = Model_Article::query()->use_view('with_comments')->count();
```

issues query like 'select count(*) from ARTICLES', not  'select ... WITH_COMMENTS'.

Please see my fix for that:
https://github.com/keigoi/orm/commit/d91d6c0b34d2879273f4538ca58c58cf981cc039

Thanks,
-- Keigo

**Comment by WanWizard** [comment]
Can you send that as a pull request on the 1.6 branch, so it can be merged with your name as author?
