### ISSUE TITLE
Empty nested relationship object

### ISSUE THREAD

**Issue by DregondRahl** [fuel/orm#21]
This returns empty 'tags' array

``` php
        $view->content = Model_Music::query()
                ->where('list_id', '=', $_list_id)
                ->related('list')
                ->related('list.tags')
                ->get_one();
```

This returns 'tags' array correctly:

``` php
        $view->content = Model_List::query()
                ->where('list_id', '=', $_list_id)
                ->related('tags')
                ->get_one();
```

Queries seems right, the ORM seems to not be sorting out the 'tags' array or something.

Edit: 'list' are related one-to-many to 'tags' and 'music' is related one-to-one to 'list' there is no relationship between 'tags' and 'music' without 'list'

**Comment by jschreuder** [comment]
Just to be sure, could you show me the queries for both with the same $list_id and a `\Debug::dump()` of the query output? (both probably best on scrapyrd.com)

**Comment by DregondRahl** [comment]
There we go, was trying different relationships, but yeah, seems SQL is fine, but something else wrong. I used a model with more data.

SQL: http://scrp.at/Va

First: http://scrp.at/Vc

Second: http://scrp.at/Vb

**Comment by dhrrgn** [comment]
Can you provide the Music, Tag and List Model code?  I want to check to make sure all the relations are correct if you don't mind.

Dan

**Comment by DregondRahl** [comment]
Model_List: http://scrp.at/VC

Model_Anime:  http://scrp.at/VD  (Same as Music, etc. SQL Dump was from this model)

Model_Tag: http://scrp.at/VE

**Comment by dhrrgn** [comment]
Shouldn't list has_many tags not list many_many tags?

**Comment by DregondRahl** [comment]
Model_List I used many_many for 'tags' because it goes through 'mini_lists_tags' (list_id, tag_id). Using has_many relationship won't build the right query that goes through the needed table.

http://scrp.at/VF

//has_many

``` sql
LEFT JOIN `mini_tags` AS `t2` ON (`t1`.`list_id` = `t2`.`tag_id`)
```

// many_many

``` sql
LEFT JOIN `mini_lists_tags` AS `t2_through` ON (`t1`.`list_id` = `t2_through`.`list_id`) LEFT JOIN `mini_tags` AS `t2` ON (`t2_through`.`tag_id` = `t2`.`tag_id`)
```

**Comment by DregondRahl** [comment]
After looking thru the code I narrowed it down so far to the hydrate function in query.php

``` php
            if ( ! array_key_exists($m['rel_name'], $rel_objs))
            {
                $rel_objs[$m['rel_name']] = $m['relation']->singular ? null : array();
            }
```

When null is changed to array() it seems to be working. Its not exactly this line that's the problem but somewhere along the way the NULL is causing the problem. I'll continue trying to find the exact spot.

EDIT: found the problem, Model_List's values are returned as an object not an array, so this line needs to be changed to have a '!'

https://github.com/fuel/orm/blob/develop/classes/query.php#L743

``` php
if (is_array($result) or ( ! is_array($result) and ! empty($result)))
```

**Comment by jschreuder** [comment]
Actually, that's  not what's wrong with the line. (it really makes no sense with that change btw)

The problem is that it uses the wrong variable, it shouldn't be `$result`, it should be `$rel_objs[$m['rel_name']]`:

```
if (is_array($rel_objs[$m['rel_name']]) or ( ! is_array($rel_objs[$m['rel_name']]) and empty($rel_objs[$m['rel_name']])))
```

The old code would only get you into trouble when loading a nested relation from a singular relation, which is what you did.

**Comment by DregondRahl** [comment]
The fix you made, seem to only retrieve only one 'tags' result and not all of them.

Dump: http://scrp.at/XD

**Comment by jschreuder** [comment]
Damn, hadn't thought of that, it can't try and skip singular relations when there's nested relations involved.
