### ISSUE TITLE
Recent commit broke things

### ISSUE THREAD

**Issue by phil-lavin** [fuel/orm#213]
Commit 2c369de3ee19a2700c3fafb391eec2f040ba62b5

With this ORM query...

``` php
$menu = \Menus\Model_Menu::find()
         ->where('title', 'Food')
         ->related('categories')
         ->where('categories.live', true)
         ->order_by('categories.position')
         ->get_one();
```

The SQL goes from this...

``` sql
SELECT `t0`.`id` AS `t0_c0`, `t0`.`title` AS `t0_c1`, `t0`.`position` AS `t0_c2`, `t0`.`live` AS `t0_c3`, `t0`.`pp_enabled` AS `t0_c4`, `t0`.`pp_image` AS `t0_c5`, `t0`.`created_at` AS `t0_c6`, `t0`.`updated_at` AS `t0_c7`, `t1_through`.`category_id`, `t1_through`.`menu_id`, `t1`.`id` AS `t1_c0`, `t1`.`title` AS `t1_c1`, `t1`.`alias` AS `t1_c2`, `t1`.`type` AS `t1_c3`, `t1`.`position` AS `t1_c4`, `t1`.`live` AS `t1_c5`, `t1`.`visible` AS `t1_c6`, `t1`.`button` AS `t1_c7`, `t1`.`banner` AS `t1_c8`, `t1`.`banner_alt` AS `t1_c9`, `t1`.`banner_link` AS `t1_c10`, `t1`.`page_title` AS `t1_c11`, `t1`.`page_description` AS `t1_c12`, `t1`.`page_keywords` AS `t1_c13`, `t1`.`created_at` AS `t1_c14`, `t1`.`updated_at` AS `t1_c15` FROM `menus__menus` AS `t0` LEFT JOIN `menus__menus_categories` AS `t1_through` ON (`t0`.`id` = `t1_through`.`menu_id`) LEFT JOIN `menus__categories` AS `t1` ON (`t1_through`.`category_id` = `t1`.`id`) WHERE `t0`.`title` = 'Food' AND `t1`.`live` = '1' ORDER BY `t1`.`position` ASC
```

To this...

``` sql
SELECT `t0`.`id` AS `t0_c0`, `t0`.`title` AS `t0_c1`, `t0`.`position` AS `t0_c2`, `t0`.`live` AS `t0_c3`, `t0`.`pp_enabled` AS `t0_c4`, `t0`.`pp_image` AS `t0_c5`, `t0`.`created_at` AS `t0_c6`, `t0`.`updated_at` AS `t0_c7` FROM (SELECT `t0`.`id`, `t0`.`title`, `t0`.`position`, `t0`.`live`, `t0`.`pp_enabled`, `t0`.`pp_image`, `t0`.`created_at`, `t0`.`updated_at` FROM `menus__menus` AS `t0` WHERE `t0`.`title` = 'Food' LIMIT 1) AS `t0` WHERE `categories`.`live` = '1' ORDER BY `categories`.`position` ASC
```

The error is such that categories does not exist. This is because it doesn't reference categories. Seems odd that it'd change a fairly efficient join into a subselect - especially one that's broken.

Checking out onto the commit below the aforementioned fixes it.

**Comment by WanWizard** [comment]
@stevewest, something broke? 

It looks like it inserts a temporal query in there (a subselect on updated_at) while it shouldn't.

**Comment by WanWizard** [comment]
That commit didn't change much in orm/model and orm/query.

What I do see is that modify_join_result() is introduced, which is called, but returns an empty array which gets merged. While in the original code the $join was actually merged. Is that intentional?

It still doesn't explain the subquery though.

**Comment by emlynwest** [comment]
I did a lot of testing before resubmitting the PR. We have been using the Temporal model our code for a while now. I'll take a look into it tomorrow but was fairly sure that existing functionality had been preserved. It's possible that something slipped through the net, even with minimal changes to existing ORM code. Unfortunately the current ORM codebase does not lend itself easy modification of this sort.

**Comment by emlynwest** [comment]
@phil-lavin Would it be possible for you to checkout the `temporal_squashed` branch from http://github.com/stevewest/orm.git , replace your current orm package with it and see if the problem has been fixed?

**Comment by phil-lavin** [comment]
In London this am - i'll check later

Sent from my iPhone

On 29 Jan 2013, at 09:58, "stevewest" <notifications@github.com<mailto:notifications@github.com>> wrote:

@phil-lavinhttps://github.com/phil-lavin Would it be possible for you to checkout the temporal_squashed branch from http://github.com/stevewest/orm.githttps://github.com/stevewest/orm.git , replace your current orm package with it and see if the problem has been fixed?

**Comment by lukearmstrong** [comment]
I have just updated to 1.6/develop, is this related to the problem I am having? 

``` php
// Get the related recipes too.
$recipes = \Recipes\Model_Recipe::query()
    ->related('products')
    ->where('products.id', '=', $product_id)
    ->get();
```

Creates this query...

```
SELECT `t0`.`id` AS `t0_c0`, `t0`.`name` AS `t0_c1`, `t0`.`ingredients` AS `t0_c2`, `t0`.`steps` AS `t0_c3`, `t0`.`order` AS `t0_c4`, `t0`.`created_at` AS `t0_c5`, `t0`.`updated_at` AS `t0_c6` FROM `recipes__recipes` AS `t0` WHERE `products`.`id` = '133' ORDER BY `t0`.`order` ASC, `t0`.`name` ASC
```

Which is wrong because it contains no join, here is the error...

```
Fuel\Core\Database_Exception [ Error ]: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'products.id' in 'where clause' with query
```

It used to work before updating to 1.6/develop.

**Comment by emlynwest** [comment]
@lukearmstrong Can you do as I asked phil-lavin and see if that resolves things?

**Comment by WanWizard** [comment]
PR merged.
