### ISSUE TITLE
ManyToMany problem resetting relations

### ISSUE THREAD

**Issue by jhuriez** [fuel/orm#214]
In ManyToMany relations, before saving the entity in the controller i want to reset the array relations, and put new/old relations.

I do this : 

``` php
// I reset all relations
$myUser->categories = array();
// I put new and old relations
foreach(Input::post('categories') as $postCategory) {
$myUser->categories[] = Model_Category::find($postCategory);
}
$myUser->save();
```

It's ok, that work. But ...

If i create an User and add 2 categories to this user, the table is like :

```
id  id_user id_category
1   1    1
2   1    2
```

And now, i want to update this User for edit other fields, but i keep his 2 categories, the table :

```
id  id_user id_category
3   1    1
4   1    2
```

He delete 2 rows for add same rows. So he delete old relations for add new relation even if it's the same relation. 
I think it's normal because i do : $myUser->categories = array();

But it's work if i do :

``` php
// Reset relations
$myUser->categories = $myUser->categories;
unset($myUser->categories);
// Put relations
foreach(Input::post('categories') as $postCategory) {
$myUser->categories[$postCategory] = Model_Category::find($postCategory);
}
$myUser->save();
```

U know what is the difference ?

-- The original thread : http://fuelphp.com/forums/discussion/11827/manytomany-relation-question-with-saveupdate --

**Comment by WanWizard** [comment]
Relation changes are tracked using the __set() and __unset() magic methods. 

This will only work if the relation has previously fetched, either by eager loading (specifying the relation on the find), or by fetching it later by accessing the property. If the related objects are not fetched, the model doesn't know which records are related, so it won't do anything with those.

**Comment by jhuriez** [comment]
Ok i see..

But what it's the best practise if i want to reset relations before saving new/old relations (for not to keep others relations that i removed from the DOM) ?

This is good ? =>

``` php
// Reset relations
$myUser->categories = $myUser->categories;
unset($myUser->categories);
// Put relations
foreach(Input::post('categories') as $postCategory) {
$myUser->categories[$postCategory] = Model_Category::find($postCategory);
}
$myUser->save();
```

or maybe i can use array_udiff()

**Comment by WanWizard** [comment]
If you want to delete all currently related objects before assigning new ones, you have to fetch and delete them individually. The related objects might have observers attached to them that act on delete, or they might have related objects of their own that need to be deleted too (because the relation defines "cascade_delete").
