### ISSUE TITLE
Temporal parent to child relationships: find_revision() returns more childen then expected

### ISSUE THREAD

**Issue by iturgeon** [fuel/orm#218]
Playing with temporal orm objects as we were about to implement our own versioning system in our app.

Anyway, given the following models:

``` php

<?
class Model_Vehicle extends Orm\Model_Temporal
{
    protected static $_properties = [
        'id',
        'name',
        'temporal_start',
        'temporal_end',
    ];

    protected static $_has_many = ['riders'];

    protected static $_temporal = ['mysql_timestamp' => false];

}

class Model_Rider extends Orm\Model_Temporal
{
    protected static $_properties = [
        'id',
        'name',
        'vehicle_id',
        'temporal_start',
        'temporal_end',
    ];

    protected static $_temporal = ['mysql_timestamp' => false];

}
```

I get somewhat unexpected results from `find_revision()` when I access the object's related children.

In this case, if I requested a specific version of the parent, I probably want a specific version of it's children.  However I receive every version of every child object this parent _ever_ had.  I am really only after the children durring that version. 

``` php
$car = Model_Vehicle::forge(['name'=>'ford']);
$dog =  Model_Rider::forge(['name' => 'Sparky']);
$car->riders[] = $dog;
$car->save();
// vehicle and rider saved

$dog->name = 'Turbo';
$dog->save();
// rider gets a revision

$dog->name = 'Ruffio';
$car->save();
// vehicle and rider get a revision even though vehicle hasn't changed?

$car->name = 'Chevy';
$car->save();
// vehicle gets a revision

$ford = Model_Vehicle::find_revision(1, $timestamp_from_ford);
$ford->riders // returns an array of all the riders AND all rider revisions related to this vehicle
```

I guess I'm wondering if the ORM should have a method to get _related_ temporal models that can restrict the results to the appropriate time?  That way a parent object can just return related children revisions from the same timestamp.

**Comment by WanWizard** [comment]
@stevewest, can you have a look at this?

**Comment by emlynwest** [comment]
I'll have a look into it. I had not noticed these problems during development but will see what I can find.

**Comment by emlynwest** [comment]
I have been able to reproduce the error except for the unwanted extra entry for vehicle, I have not been able to reproduce it. Hopefully should have a fix today, time permitting.

**Comment by emlynwest** [comment]
It would appear that no temporal filtering is performed when relations are lazy loaded. If you where to do:

``` php
$ford  = Model_Vehicle::find_revision(1, $timestamp_from_ford, ['riders']);
```

Only a single rider is returned by `$ford->riders`, as intended.

@iturgeon I will implement a fix for lazy loading but for now you can specify the names of the relations when using `find_revision()` as the 3rd parameter to get around this problem.

**Comment by iturgeon** [comment]
Awesome @stevewest , I can verify the changes fix lazy loading related models when using `find_revision`.

**Comment by emlynwest** [comment]
@iturgeon Great! Thanks for posting the ticket. I hope that temporal provides the functionality that you are looking for.
