### ISSUE TITLE
Temporal related failures on save can leave parent in 'deleted' state

### ISSUE THREAD

**Issue by iturgeon** [fuel/orm#225]
When a related child throws and error durring save, the parent object has updated it's temporal_end to now, but fails to save the children AND fails to write the new row for itself... effectively leaving it in a deleted state.

``` php
$parent = Model_A::forge();
$parent->save(); // yay!
$parent->children[] = Model_B::forge();
$parent->save(); // imagine $Model_B::save() throws error; now $parent is expired/deleted
```

I haven't had time yet to figure out the best solution, at the very least a try/catch around the parent::save() will save the parent back into the table (writes a 2nd row).

I'm thinking the most desirable thing for it to do is revert it's timestamp and throw an error?

**Comment by iturgeon** [comment]
Excluding transactions, with the existing ORM, if a related model throws an error, am I right that the parent object will retain it's changes?

I think it does, so I feel that here with temporal models: in the event that the related objects throw an error we should capture the error, save the parent object and throw it again?

**Comment by emlynwest** [comment]
I think the most simple fix for this would be to process relations before saving the parent object (and creating the new revision). Although this would cause the problem of relations not having an ID to relate to if the parent object is new. 

Like you say the best way might to be to catch errors while saving relations, revert the timestamp changes to the parent and throw the error on. The problem I see happening here is that some children will be updated while others will not, I am not too sure how to handle those, it will not be easy to revert the saved changes as the original data is reset with the new data after `save()`
