### ISSUE TITLE
count_by_ behaves the wrong way

### ISSUE THREAD

**Issue by huglester** [fuel/orm#23]
Hello,

$a = Model_Reviewcomment::count_by_review_id($review_id); 
Is generating the wrong SQL query.
it generates: SELECT COUNT(t0.id) AS count_result FROM `reviewcomments` AS `t0` 

the provided SQL omits the needed where clause:
 'WHERE review_id = ....'

**Comment by jschreuder** [comment]
Could you try this again? From what I see this works as expected with latest develop.

**Comment by huglester** [comment]
Hello,

thanks, confirmed to work :)
