### ISSUE TITLE
Query with related, order_by and limit return wrong result

### ISSUE THREAD

**Issue by Baldinof** [fuel/orm#235]
# The problem

when having a query with related + limit/offset + order_by, the result are different of what's expected.
# Why ?

The problem is with the `order_by` position in generated SQL. The query builder create a subquery with the `limit`, but `order_by` is in the global query.

When MySQL runs the subquery it limits the result with the given limit. I understand the reason of placing limit in subquery and i'm agree. 
But without the `order_by` in subquery, MySQL is ordering by the ID (by entry order in table). So when limiting, it's not limiting on the good result and finally the joins are not on good result too.

Example : 

``` PHP
$foo = Model_Post::query()
          ->related('comments')
          ->order_by('publish_date')
          ->limit(4)
          ->get();

$bar = Model_Post::query()
          ->order_by('publish_date')
          ->limit(4)
          ->get();
```

Actually the result will not be the same ! (if the publish_date sort are different of the entry date in table of course)

**Comment by ghost** [comment]
Are you sure you're not just looking for the following functions:

->rows_limit(4)
->rows_offset()

From the docs: http://fuelphp.com/docs/packages/orm/crud.html

**Comment by WanWizard** [comment]
The limit and offset in queries with related objects are used on the parent, not on the entire query result. The order_by however, is always done on the result.

So the comment is correct, if you need a limitative list (for example for pagination), use rows_limit/rows_offset to the limit is applied in the same place as the order_by, on the final result.

**Comment by wkiril** [comment]
what if someone needs to show last 5 posts with its comments on the same page - rows_limit will limit the comments as well

**Comment by Baldinof** [comment]
Sorry if I have not answered before

The problem is exactly what wkiril said.

`rows_limit` can't be used as we don't know how many rows we need.

Currently we can't retrieve the **last 5 posts with its comments** using _eager loading_.

**Comment by WanWizard** [comment]
Ok, understand the use case now.

**Comment by Baldinof** [comment]
Perfect!

**Comment by WanWizard** [comment]
Thanks for the feedback. Let us know if you encounter side-effects.

**Comment by vesselinv** [comment]
Brilliant! Thanks for solving this! :)
