### ISSUE TITLE
Relation condition 'join_on' never makes it into the query

### ISSUE THREAD

**Issue by JaapRood** [fuel/orm#238]
Given the following query (straight out of my project)

``` php
$member_query = \Model_Project_Member::query(array(
    'related' => array(
        'notifications' => array(
            'join_type' => 'left',
            'join_on' => array(
                array('state', '=', 'unseen')
            )

        )
    )
));
```

the `get_query` method produces the following:

``` sql
SELECT `t0`.`role`              AS `t0_c0`, 
       `t0`.`id`                AS `t0_c1`, 
       `t0`.`project_id`        AS `t0_c2`, 
       `t0`.`user_id`           AS `t0_c3`, 
       `t0`.`created_at`        AS `t0_c4`, 
       `t0`.`updated_at`        AS `t0_c5`, 
       `t1`.`state`             AS `t1_c0`, 
       `t1`.`id`                AS `t1_c1`, 
       `t1`.`project_member_id` AS `t1_c2`, 
       `t1`.`event_id`          AS `t1_c3`, 
       `t1`.`created_at`        AS `t1_c4`, 
       `t1`.`updated_at`        AS `t1_c5` 
FROM   `projects_members` AS `t0` 
       LEFT OUTER JOIN `projects_members_notifications` AS `t1` 
                    ON ( `t0`.`id` = `t1`.`project_member_id` ) 
WHERE  `t0`.`id` = 1 
```

Isn't there supposed to be a second ON clause for joining the notifications now? I had a quick glance at `Orm\Query` but must admit I'm to unfamiliar with the codebase to make any educated guesses for where stuff hits the fan.

Using as documented [in the docs](http://fuelphp.com/docs/packages/orm/relations/intro.html#join_types) and with latest 1.6/develop (e794626efbd2ab9853db8d60e740bf4b94787fa6)

**Comment by hackoh** [comment]
@JaapRood 
Can the following fix help you?
https://github.com/hackoh/orm/compare/1.6;query_join_on

**Comment by JaapRood** [comment]
Took a while for me to get an opportunity to test, but yes! So the code to handle 'join_on' is just completely missing from the relationship?

**Comment by JaapRood** [comment]
@hackoh seems to hold up pretty well. Planning a PR?

**Comment by hackoh** [comment]
@JaapRood 
Also about the other relationships will need to be addressed as well.
When that is completed, I'm planning a PR.
Could you wait patiently a little?

**Comment by JaapRood** [comment]
@hackoh awesome, thanks a bunch :+1:

**Comment by ghost** [comment]
Looked over the commit you referenced @hackoh, and had this followup question: Will your fix also account for the method-chaining method?  E.g. from docs: 
Model_Article::query()
    ->related('author', array('where' => array(array('active', '=', 1), array('status', '=', 'X'))));

Source: http://fuelphp.com/docs/packages/orm/crud.html

Thanks,
Tony

**Comment by hackoh** [comment]
@TonyAlleluu 
If you meant about using 'join_on' in the related-conditions, I say 'Yes'.
But if you meant about 'where', It is not related to this fix.

**Comment by ghost** [comment]
I'll go ahead and create a separate issue then.  Thanks!

Tony
