### ISSUE TITLE
many-to-many problem with first row relation

### ISSUE THREAD

**Issue by konradlipner** [fuel/orm#240]
I'm new to this library and quite newbie in PHP. I have a strange problem while working with Warden: roles assigning works for every user, except with ID 1. Here is the code:

```
        $user = Model_User::find($id);
        $roles = array();
        if (Input::post('role')){
            foreach (Input::post('role') as $selected_role) {
                $roles[$selected_role] = Model_Role::find((int)$selected_role); 
            }
        }
        $user->roles=$roles;
```

I did some debugging and found out that in Model_User _event_before_save() calls _add_default_role() and finally in there I've found line:

if (empty($this->roles) || !static::query()->related('roles')->get_one()

seems that this static::query do some magic and as a (possibly unwanted) result in my $user object in _original_relations property gets roles inserted with values i want to add. In this case when I finally got to orm\classes\model.php:save() and call manytomany.php:save() with $_original_relations passed as $original_model_ids parameter and perform:

```
    // Check if the model was already assigned, if not INSERT relationships:
    if ( ! in_array($current_model_id, $original_model_ids))
```

condition detects that change in DB is already done, and does not perform insert!
I made workaround in Warden, but the issue is still there.

BR

**Comment by WanWizard** [comment]
This looks like an issue in Warden, not in the Orm. So this report doesn't belong here.

Note that assigning new child objects to a parents relation DOES NOT delete existing relations. If you want to replace existing roles in the database, do an `unset ($user->roles);` first.
