### ISSUE TITLE
Connecting to Multiple Databases

### ISSUE THREAD

**Issue by patie** [fuel/orm#25]
it would be good if Orm supported joining (/or switching) of multiple databases (of course without support for joining between connections)

a) setting database models in each group (if is not set will use the default connection) in case that the application needs to connect to multiple databases

or

b) Possibility switching database group? in controller? (for example when application uses more languages ​​- but tables are same - one database = one language)

**Comment by jschreuder** [comment]
How it will be implemented most likely, I'll try and get it in for 1.0 but for now scheduled for 1.1:
- nu support for joins between connections, will throw an error when querying shows the related model has a different DB
- connection can be set as a model property, the default connection is assumed when none is set
- connections of course will need to be setup in app/config/db.php, only those can be used

**Comment by lekoala** [comment]
I just had the same problem, if you want a basic solution, you can add a database property to the orm\model and edit all the calls in orm\query to execute to call this static property (similar to calls to static table method)
that seems to work for basic operations.

**Comment by jschreuder** [comment]
Isn't that exactly what I described above? Commit it to a fork of your own & pull-request, will save me some time and give you a free code review...

**Comment by patie** [comment]
i will try, but will be better if there will be built in

**Comment by jschreuder** [comment]
@patoman huh? That's exactly what the idea is, I was just asking lekoala to submit his solution.

**Comment by lekoala** [comment]
here you go

**Comment by patie** [comment]
when i extend orm model class about something like that

```
    public static function set_conn($conn)
    {
        static::$_connection = $conn;
    }
```

will be possible switching between databases "on the fly" right ?

**Comment by jschreuder** [comment]
Probably, but I wouldn't recommend it - nor would I consider this something that should be supported.

A model and its ID should be unique, if you're fetching the same model from multiple tables they're not and you'll run into trouble because of that.
