### ISSUE TITLE
Cascade delete fails when extending Orm\Model_Soft

### ISSUE THREAD

**Issue by mikelexp** [fuel/orm#250]
It throws an exception with the message "Orm\FrozenObject [ Error ]: No changes allowed.", but cascade delete works fine when you extend Orm\Model instead of Model_Soft.

**Comment by emlynwest** [comment]
Looking into this now.

**Comment by emlynwest** [comment]
What type of relation are you using? I am not able to reproduce this error.

**Comment by mikelexp** [comment]
Well right now I can't reproduce it myself. It was a simple has_many / belongs_to relationship (the typical Categories/Products, etc). I wrote about it in the forums and Harro said that cascade delete with soft delete wasn't supported, that's when I thought it was a real bug. If I see it again sometime, I'll let you know. Issue closed, thank you!

**Comment by emlynwest** [comment]
Thanks for confirming. Just reopen the ticket if you can get it to reproduce reliably.

**Comment by emlynwest** [comment]
I have been able to reproduce this so going to re-open the ticket and look into it.

**Comment by mikelexp** [comment]
Wow, that's amazing, thank you Steve!
