### ISSUE TITLE
"Trying to get property of non-object" in Belongs To Relationships

### ISSUE THREAD

**Issue by awgneo** [fuel/orm#255]
I think the swap from mode_from to model_to is wrong in the "pick the correct model to compare keys with..." change in the orm/classes/belongsto.php file as I am getting a "Trying to get property of non-object" on like 159. Switching these back to model_from in the 1.6 release fixes my belong_to relationships.

**Comment by WanWizard** [comment]
Do you have a code sample on how you use it?

**Comment by emlynwest** [comment]
@WanWizard https://github.com/fuel/orm/commit/30261e2e49f3a23b8c3f51db749ae18cc6c4a5e1#commitcomment-3165757

**Comment by WanWizard** [comment]
Ok, so the issue is not that the use of passed objects is incorrect, but that there's a race condition in which null is passed, and which is not handled. I'll have a look later today.
