### ISSUE TITLE
->save() always return false when save item with predifined primary keys

### ISSUE THREAD

**Issue by yahorosh** [fuel/orm#257]
You using LAST_INSERT_ID() mysql function for detect of succsefulity INSERT queries.

in core/classes/database/pdo/connection.php:213

``` php
            return array(
                $this->_connection->lastInsertId(),
                $result->rowCount(),
            );
```

and then you check success in 

packages/orm/classes/query.php:1276

``` php
        if ($res[0] === 0)
        {
            return false;
        }
```

But i use predifined primary key.
ie

``` php
Item = Items::forge($data, true);
Item->id = 123;
Item->save(); // I always get 'false' without any error
```

Because LAST_INSERT_ID() would return 0 every time when we type primary key in insert.

http://dev.mysql.com/doc/refman/5.1/en/information-functions.html#function_last-insert-id

**Comment by WanWizard** [comment]
It should not check the last-insert-id, it should check the row count, which is always 1 on a succesful insert.
