### ISSUE TITLE
Model_Soft::should_cascade_delete does not check if cascade_delete is false

### ISSUE THREAD

**Issue by jverb** [fuel/orm#261]
Using latest 1.6/master, Model_Post has relationship defined as: 

``` php
protected static $_has_many = array(
        'views' => array(
            'key_from' => 'id',
            'model_to' => 'Model_Post_Views',
            'key_to' => 'post_id',
            'cascade_save' => false,
            'cascade_delete' => false,
        ),
    );
```

Throws error: "Both sides of the relation must be subclasses of Model_Soft or Model_Temporal if cascade delete is true. Model_Post_Views was found instead."

The relationship cascade delete is not true and thus this should not be an error. Needs to check if cascade delete is false first.

**Comment by emlynwest** [comment]
I am not able to recreate this issue in 1.7/develop. Can you post the full model code and the exact code you are using that triggers this error?

**Comment by WanWizard** [comment]
@jverb any update on this?

**Comment by jverb** [comment]
Sorry for the delayed update.  This is still not fixed. My situation is that I have a table for uploaded files and one that tracks views on those files (call it upload_files and upload_file_views) on a file. The records upload_file_views are related to the upload_files record. But they have no need for the additional complexity of soft delete nor do they need to be "deleted" when a record in upload_files is soft deleted. This is because other functionality shows analytics of historical views on all of their files even if deleted.  The problem is here in model/soft.php:

``` php
protected function should_cascade_delete($rel)
    {
        //Because temporal includes soft delete functionality it can be deleted too
        if ( ! is_subclass_of($rel->model_to, 'Orm\Model_Soft') && ! is_subclass_of($rel->model_to, 'Orm\Model_Temporal'))
        {
            //Throw if other is not soft
            throw new RelationNotSoft('Both sides of the relation must be subclasses of Model_Soft or Model_Temporal if cascade delete is true. '.$rel->model_to.' was found instead.');
        }

        return true;
    }
```

This does not check if cascade_delete is true or false before requiring that the rel be soft or temporal subclass. If the cascade_delete set to false, I see no reason that the relationship should also have to be subclass of soft or temporal as it will have no effect on the sql transaction. 

A simple solution would be to add something like this:

``` php
if ( $rel->cascade_delete && ! is_subclass_of($rel->model_to, 'Orm\Model_Soft') && ! is_subclass_of($rel->model_to, 'Orm\Model_Temporal'))
```

I hope that helps clear things up.

**Comment by emlynwest** [comment]
I see the problem now. And it would be quite reasonable to include the cascade check. I'll take a look at doing that this week if I get some time. Or if you create a pull request I'll take a look.
