### ISSUE TITLE
Observer_Slug in Model_Temporal

### ISSUE THREAD

**Issue by sagikazarmark** [fuel/orm#264]
Observer_Slug in Model_Temporal creates new slug for every revision of the same entity on before_insert event.

**Comment by emlynwest** [comment]
This is unfortunately unavoidable behaviour as `Model_Temporal` performs an extra insert when updating.

**Comment by sagikazarmark** [comment]
Can it be solved somehow with observers? Or I have to do it manually from my model?
How can I make difference between the Model which contains the last revision and the cloned Model?
My idea: register the observer only when the Model is not a revision.

**Comment by WanWizard** [comment]
Observer_Slug runs a query to check if the slug is unique.

As the current model object is passed to it, it should be possible to check if it's an instance of Model_Temporal, and if so, add a where clause to the query to only check against the current revisions?

**Comment by sagikazarmark** [comment]
The observer runs when I save the model, so a new revision is inserted, so the "main" revision always have the original slug, and the older revisions get new ones. I think in this case  checking against current revisions don't solve the problem (as all revision of an entity should have the same slug). The actual problem is (maybe I was not clear) that the older revisions get new slugs not the current one.

So in this case the expected functionality is that Observer_Slug runs only when a new entity is inserted.

Possible solutions:
Override `create()` and only call `before_insert` when a new entity (not a revision) is inserted.
Downside: there is no `before_insert` for inserting a revision and a bit ugly because of the overriding.

Create a new observer event for temporal model new entity inserting, and call that when saving the model.
Downside: not compatible with the included observers, so they have to be extended.

**Comment by WanWizard** [comment]
It should be dealt with in the observer. If you start messing with conditionally calling observers, it will quickly become an uncontrollable mess, observers should always be called, that's why they are called observers.

It is up to the observer to "observe" whether or not the model object passed is of interest.

**Comment by sagikazarmark** [comment]
Yes, you are right, I solved it this way, but I think this should be somehow included in ORM. I overrided the Observer_Slug, so I only have before_insert on new entities.

**Comment by sagikazarmark** [comment]
Yes, you are right, I solved it this way, but I think this should be somehow included in ORM. I overrided the Observer_Slug, so I only have before_insert on new entities.

**Comment by WanWizard** [comment]
@stevewest, would this check work?

``` php
// construct the query
$query = $obj->query()->where($this->_property, 'like', $slug.'%');

// is this a temporal model?
if ($obj instanceOf Model_Temporal)
{
    // add a filter to only check current revisions
    $class = get_class($obj);
    $query->where($class::temporal_property('end_column'), '=', $class::temporal_property('max_timestamp'));
}

// do we have records with this slug?
$same = $query->get();
```

to make sure it only checks the current revisions? By the time it gets to this check, the models' save() method has already assigned a new end timestamp to the old last revision, so that will be filtered too.

**Comment by sagikazarmark** [comment]
I think this won't solve the problem I mentioned.  The old revision is the inserted row not the current one, so by the time it gets to this check, there is still a current revision of the same entity with the same slug and always will be. Maybe checking for current revisions with different entity ID? This way the current revision of the same entity will be filtered out, so only other entities will be checked.

The only problem with this is that a new entity will not have an ID to check. And actually when inserting an old revision there is no need to check for an existing slug, as we know that it exists. It should only be checked when the insert is a new entity.

Hm...I am not so clear, but I hope you can understand me. :)

``` php
// construct the query
$query = $obj->query()->where($this->_property, 'like', $slug.'%');

// is this a temporal model?
if ($obj instanceOf Model_Temporal)
{
    // add a filter to only check current revisions except the current entity
    $class = get_class($obj);
    $query->where($class::temporal_property('end_column'), '=', $class::temporal_property('max_timestamp'));
    $query->where('id', 'IS NOT', $obj->id);
}

// do we have records with this slug?
$same = $query->get();
```

``` php
// construct the query
$query = $obj->query()->where($this->_property, 'like', $slug.'%');

// is this a temporal model?
if ($obj instanceOf Model_Temporal)
{
    $class = get_class($obj);
   if ($obj->temporal_end != $class::temporal_property('max_timestamp'))
   {
      $same = null;
   }
}

$same = isset($same) ?: $query->get();
```

**Comment by WanWizard** [comment]
Hmmm... Missed that, it does save the cloned object first, so that would probably be inserted.

It would have to filter out all records of the same PK, for which you need getNonTimestampPks(), which is currently defined private, so that would need to change. Then with that info you can construct a where clause to filter based on the PK values of the current object.

**Comment by sagikazarmark** [comment]
Like this:

``` php
// construct the query
$query = $obj->query()->where($this->_property, 'like', $slug.'%');

// is this a temporal model?
if ($obj instanceOf Model_Temporal)
{
    // add a filter to only check current revisions except the current entity
    $class = get_class($obj);
    $query->where($class::temporal_property('end_column'), '=', $class::temporal_property('max_timestamp'));
    foreach($class::getNonTimestampPks() as $key)
    {
        $query->where($key, '!=', $obj->{$key});
    }
}

// do we have records with this slug?
$same = $query->get();
```

Maybe it needs checking that the property exists in the Model.

**Comment by WanWizard** [comment]
that would probably work, but I think that requires getNonTimestampPks() to be defined public.

@stevewest?

**Comment by sagikazarmark** [comment]
You are right, I missed that.

**Comment by emlynwest** [comment]
Sorry for the late reply. I don't really have any time for fuel related things at the moment. I can't see a problem with making `getNonTimestampPks()` public.

**Comment by WanWizard** [comment]
No problem, I'll have a look later.
