### ISSUE TITLE
Model_Temporal query returns all revisions

### ISSUE THREAD

**Issue by sagikazarmark** [fuel/orm#265]
There is the following table structure

``` php
        \DBUtil::create_table('repositories', array(
            'id' => array('constraint' => 11, 'type' => 'int', 'auto_increment' => true, 'unsigned' => true),
            'temporal_start' => array('constraint' => 11, 'type' => 'int'),
            'temporal_end' => array('constraint' => 11, 'type' => 'int', 'null' => true),
            'name' => array('constraint' => 512, 'type' => 'varchar'),
            'slug' => array('constraint' => 512, 'type' => 'varchar'),
            'type' => array('constraint' => 32, 'type' => 'varchar'),
            'version' => array('constraint' => 16, 'type' => 'varchar'),
        ), array('id', 'temporal_start', 'temporal_end'));
```

Queries from this table includes all revisions, not only the last one:

``` php
        $result = Model_Repository::query()
            ->where('temporal_end', Model_Repository::temporal_property('max_timestamp'))
            ->where('type', $type)
            ->get();
```

The query above includes the required where condition, which is included in find, but not in query. Without this condition the query returns all revisions.

The interesting thing is that count() returns the right number of entities.

**Comment by emlynwest** [comment]
Due to the fact that the `count()` returns the correct number of entries in the array I am a little doubtful if this is a temporal problem or not (Just a little though). What version of the orm are you using? I fixed something like this rather recently.

**Comment by sagikazarmark** [comment]
I am using the 1.7/develop version. Actually the count is working beacuse of DISTINCT counting of the id, but there is neither where condition for temporal_end in count() nor in query().

**Comment by WanWizard** [comment]
I find it odd that count() would return the correct value, since that did use a default Query instance hardcoded, and would never filter anything. 

I just changed that to use an overloaded query() method if present, so now count(), min() and max() will use the overloaded query() method, which does add the correct filtering for both Model_Soft and Model_Temporal.

**Comment by sagikazarmark** [comment]
As I mentioned the count() used DISTINCT, so it counted every id only once. There was no condition in the query, so probably it was a special case that it seemed to be working.

**Comment by WanWizard** [comment]
@stevewest is this still an issue or can it be closed?

**Comment by emlynwest** [comment]
I think this is still an issue.

**Comment by sagikazarmark** [comment]
I think this has been fixed.
