### ISSUE TITLE
Query hydrate always type casts primary keys.

### ISSUE THREAD

**Issue by ghost** [fuel/orm#267]
Primary keys are always type casted during hydration. It would be nice to include a config setting where this could be disabled/customized and would increase clarity that type casting occurs.

**Comment by WanWizard** [comment]
They are the glue that keeps relations together, it would be a bad idea to allow mixed typing, everything would fail (as it would require all checks to be done using loose comparison, which means all of a sudden 0 == "A"). So this can not be implemented.
