### ISSUE TITLE
Model_Soft cascade-delete is not work.

### ISSUE THREAD

**Issue by takyam-git** [fuel/orm#269]
I try cascade-delete `Model_Soft` with `has_many`, `belongs_to` and `has_one`.
But all case delete only specific model, and not deleted relational models.

Please see my tries on [Gist https://gist.github.com/takyam-git/0ad9cccf204a9576c712 ](https://gist.github.com/takyam-git/0ad9cccf204a9576c712).

I was checked fuel/orm on version 13518c44e20d50f373c4b10764379901bf3c953b .

**Comment by WanWizard** [comment]
Duplicate. See #261
