### ISSUE TITLE
ORM Model_Soft With Related Table Not Work Well

### ISSUE THREAD

**Issue by r90** [fuel/orm#275]
Hello.
I'm from FuelPHP Forum to report bug.

I created a query that contains two models extending Model_Soft.
I defined the `protected static $_soft_delete` property In both models.

But is does not work, the generated SQL is:

```
SELECT `tbl_t0`.`id` AS `t0_c0`....
LEFT JOIN `tbl_reports` AS `tbl_t1`
ON (`tbl_t0`.`id` = `tbl_t1`.`user_id` AND `tbl_t1`.`delete_time` IS NULL ) 
```

Where Is `tbl_t0.delete_time` ?

(more detail of this in the forum)

**Comment by WanWizard** [comment]
fixed in #261
