### ISSUE TITLE
to_array() on dump_tree(true) does not cascade

### ISSUE THREAD

**Issue by philipptempel** [fuel/orm#279]
Performing a `to_array()` on a result from `dump_tree(true)` does not cascade i.e., something like this

``` php
$roles = \Model\Role::forge()
    ->root()
    ->get_one()
    ->dump_tree(true);

\Debug::dump($roles->to_array());
```

results in an array for the root-node but the nodes below 'children' (and their children) are still all of type Orm\Model_Nestedset e.g.,

``` php
Variable #1:
  (Array, 8 elements) ↵
     children (Array, 3 elements) ↵
         4741165356817169 (Object #63): Orm\Model_Nestedset ↵

         8467357664215735 (Object #65): Orm\Model_Nestedset ↵

         4296539178188649 (Object #67): Orm\Model_Nestedset ↵

     resource_id (Integer): 2971968431872421
     name (String): "ROOT" (4 characters)
     slug (String): "" (0 characters)
     created_at (String): "1372068984" (10 characters)
     updated_at : null
     lft (String): "1" (1 characters)
     rgt (String): "8" (1 characters)
```

This also means, that `dump_tree(false)` does not yield the same result as `dump_tree(true)->to_array()`, as you'd expect, as long as I'm not mistaking the design of the model itself ;)

I'm trying to get my head around making a pull request, but I don't know where to insert the fix properly to not just fix this problem but also naut to cause any other problems ;)

**Comment by WanWizard** [comment]
PR was merged.
