### ISSUE TITLE
Primary key on model ModelName cannot be changed.

### ISSUE THREAD

**Issue by lukrizal** [fuel/orm#294]
I have this table named Temp_Vars, it is like a session table that holds temporary variables render by the system or the user. It has 4 columns named `'id', 'name', 'value', 'user_id'`. I used the setup for almost 2 weeks when decided to removed the `'id'` column and have a `('name','user_id')` set up as the **primary key**. And when I re-run the program, I have this error saying: `Primary key on model <ModelName> cannot be changed`.

Why FuelPHP is not allowing to write on not-incrementing primary key?

Note: **FuelPHP ver 1.7**, `'user_id'` is a **foreign key** referencing to another table.

**Comment by emlynwest** [comment]
Primary keys cannot be changed. If anything tries to change `user_id` or `name` this error will be thrown. It only applies to existing data, of course you can set the PK for a new model if needed.

**Comment by lukrizal** [comment]
I reconstructed the table, removing the `'id'` column and defining the two existing columns `'name'` and `'user_id'` as the primary key. That's it, as in fresh copy of the table--no data. And also, the error is appearing when I'm inserting a new record.

**Comment by emlynwest** [comment]
If `user_id` is used in a relation then it will cause issues with the ORM. Fuel's ORM expects foreign keys to not be primary keys. If you do use a FK as a PK then it will cause issues when saving/deleting models with relations.

**Comment by lukrizal** [comment]
yeah. you are right.

**Comment by emlynwest** [comment]
Generally I try to design my DB to take this into account. Happy I could clear this up for you.
