### ISSUE TITLE
Shouldn't Model_Temporal::query()->update() create a new revision?

### ISSUE THREAD

**Issue by sagikazarmark** [fuel/orm#296]
This could be a good feature, as the data itself doesn't have to be selected.

It doesn't have to replace the default update method, could be update_temporal()

**Comment by emlynwest** [comment]
I don't understand the problem here. There is a `overwrite()` method that will perform a save without adding a new row, it will update the old one instead.

**Comment by sagikazarmark** [comment]
I don't know what `overwrite()` does, but `Model_Temporal::query()->update()` updates the data without fetching it into the model. It is only running UPDATE without SELECT. But: this could also insert a new row in case of temporal model.

To tell the truth: I am not so sure now, that would be a good feature. :smile:

**Comment by emlynwest** [comment]
I am currently looking at restructuring the current temporal code so as much of the filtering/update logic happens in the query object. If it goes well this will solve this problem and potentially a few other temporal related issues.
