### ISSUE TITLE
Dump EAV to array

### ISSUE THREAD

**Issue by sagikazarmark** [fuel/orm#303]
I am thinking about the implementation of dumping EAV attributes in to_array().

What do you think?

**Comment by sagikazarmark** [comment]
@WanWizard can you check this? Actually I already implemented it, but I don't want to PR unless I know that this is not forbidden or something :smile:

**Comment by sagikazarmark** [comment]
@stevewest can you check this out?

**Comment by emlynwest** [comment]
EAV is not my domain, you will need @WanWizard's input for this. IMO the best thing would be to code it up and create a pull request then we can take a look at what you propose. Personally I don't use EAV much and have never had to use `to_array()` with it but I could see how it might be useful.

**Comment by WanWizard** [comment]
EAV data is already available in to_array() output, as underneath it's a plain one-to-many relation?
