### ISSUE TITLE
Regression on unset() many_many relation

### ISSUE THREAD

**Issue by felixgilles** [fuel/orm#304]
Seem that [this change](https://github.com/fuel/orm/commit/20b596f3242971b198e998eb421d7d78284f65ec#diff-7432e43adaa222594e5951f55d73ebd3R920) in 20b596f3242971b198e998eb421d7d78284f65ec has introduced a regression

Scenario:
We have a Model_Post that has a many_many relation named categories. 

``` php
$post = Model_Post::find(1);
\Debug::dump($post->categories);
// an array() containing one Model_Category with ID 1
unset($post->categories);
$post->categories = array(
  Model_Category::find(1),
  Model_Category::find(2),
);
$post->save();
```

Before 20b596f3242971b198e998eb421d7d78284f65ec, works fine, categories relation for the post with ID 1 contains two Model_Category (IDs 1 and 2).
After, categories just contains one Model_Category (ID 2).

When saving post, all categories relations are deleted by delete_related() call. The save() on categories relation inserts just items which ID is not in original relation: https://github.com/fuel/orm/blob/1.7/develop/classes/manymany.php#L264

**Comment by WanWizard** [comment]
Not a lot of time at the moment to look into this.

Can you find this line in Orm\Model, in the save() method:

```
$rel->delete_related($this);
```

and add after it

```
$this->_original_relations[$rel_name] = $rel->singular ? null : array();
```

and check if this fixes it?

**Comment by felixgilles** [comment]
I'm in vacation today, but I will test that tomorrow.

**Comment by WanWizard** [comment]
Setup some tests myself.

When you don't use the unset, but just assign the new values using the array (which implicitly resets all relations) it works fine. If the unset is there, it shows the behaviour you reported. The fix about does indeed fix it, so I'll push that in a moment.

**Comment by felixgilles** [comment]
Nice, thank you !
