### ISSUE TITLE
Make Orm\Query group_by() method alias aware

### ISSUE THREAD

**Issue by Savageman** [fuel/orm#307]
So we can use `->group_by('categories.id')` for instance.

**Comment by WanWizard** [comment]
Just wrote some test code, but I don't have a problem with that here, it gets replaced by `t1.id` without problems?

**Comment by Savageman** [comment]
Hum, I just checked too and it was added recently with 408710f540c0ace3cac252b8b7408a6e19cecb96 . We don't have this yet, we'll update :) 
Sorry for the time you spent :'(
