### ISSUE TITLE
postgresql doesn't like delete with "LIMIT"

### ISSUE THREAD

**Issue by maitrepylos** [fuel/orm#311]
Hello, it seemed to me to have seen somewhere that the concern of database\query\builder\delete.php with the limit and PostgreSQL would quickly be solved, this problem FuelPhp 1.7 still exist.

My solution was to spread the class. See discussion http://fuelphp.com/forums/discussion/12273

MaitrePylos

**Comment by WanWizard** [comment]
Problem in general is that the entire 1.x codebase is pretty much MySQL centric. There are a lot more places (for example the entire DBUtil class, the fact that an autoincrement PK is expected in lots of places) that don't play ball with other RDBMS engines very well.

It's the main reason Fuel v2 will have a complete new Database package, that will fully support multiple platforms.

**Comment by maitrepylos** [comment]
OK thanks, it is possible to see the code of 2.0?

**Comment by WanWizard** [comment]
https://github.com/fuelphp/database

**Comment by maitrepylos** [comment]
OK, you based yourselves on Doctrine.

Thank you

**Comment by WanWizard** [comment]
No, we didn't. You probably didn't look any further than the readme. 

We use the schema builder from Doctrine, because it's good, platform independent, and fast. We don't use anything else from doctrine.

**Comment by maitrepylos** [comment]
Effectively I had not read up to the end.

Sorry.

**Comment by WanWizard** [comment]
@FrenkyNet @stevewest anyone have any objections on removing the "LIMIT 1" on the DELETE? Any side-effects that you can see?
