### ISSUE TITLE
Query constructor table alias

### ISSUE THREAD

**Issue by sagikazarmark** [fuel/orm#317]
In Orm Query constructor there is an argument called $table_alias, which is not used, but would be very useful. But there is no option for this in forge, so it cannot be set.

What is that argument for? It could be very useful, If that is what I think it is.

Is it for specifying a custom alias for that table?

**Comment by WanWizard** [comment]
I think it is a left-over, it isn't actually used anywhere in the class. Table aliasses are generated dynamically by the Query class. I checked the files history, it has always been there, and never used.
