### ISSUE TITLE
ORM Model clone() doesn't work

### ISSUE THREAD

**Issue by WanWizard** [fuel/orm#32]
If you do, you'll get

```
Orm\Exception [ Error ]: Primary key cannot be changed.
```

Looks like the reset of the primary keys doesn't work, because it gets blocked in __set().

Possible workaround:

```
    // Reset primary keys (work around a __set() limitation)
    $keys = static::$_primary_key;
    static::$_primary_key = array();
    foreach ($keys as $pk)
    {
        $this->{$pk} = null;
    }
    static::$_primary_key = $keys;
```

**Comment by jschreuder** [comment]
A cleaner workaround would be to change the PKs through $this->_data[$pk]

**Comment by WanWizard** [comment]
Does that alter the value of $this->{$pk} indirectly?

**Comment by jschreuder** [comment]
The `__set()` method uses either the `$this->_data` or a relation, because the primary keys will always be in the `$this->_data` array we can do it directly. The __set() method shouldn't be allowed to change PK's itself, those should be fixed or everything may fall apart when those are changed.
