### ISSUE TITLE
Observer_CreatedAt overwrite value

### ISSUE THREAD

**Issue by dercoder** [fuel/orm#321]
The CreatedAt overwrite my set value.
Example: 

``` php
$model = \Model_Test::forge();
$model->name = 'Test 1';
$model->created_at = '2013-11-23 14:32:19';
$model->save();
```

But the current date will be saved. It would be nice when the observer dont overwrite the data. Example usage would be when i want to import today data from last week and set the created_at date from external service

**Comment by emlynwest** [comment]
If you want to set your own date then you need to remove the observer. It will always override the given value if the saved object is new. If you wanted this functionality it would be best if you implemented your own `CreatedAt` observer to provide what you need.

**Comment by WanWizard** [comment]
@stevewest Not entirely agreed. Problem is that the observer config is a per-model setting, so it's either there, or it isn't. You can't toggle it usage at runtime.

I don't have a problem with having the observer set it only if it's isn't already set.

**Comment by dercoder** [comment]
Yes, thats why i need this code change. Optionial it would be nice to set a value if overwriting is allowed or not

**Comment by WanWizard** [comment]
Was already working on that ;)

**Comment by dercoder** [comment]
Very nice :+1:

**Comment by WanWizard** [comment]
done and documented. Original behaviour is default.
