### ISSUE TITLE
Temporal moel find_revision first/last

### ISSUE THREAD

**Issue by sagikazarmark** [fuel/orm#323]
Model_Temporal::find_revision could accept 'first' as timestamp paramater, so the first revision of the same entity could be returned

**Comment by emlynwest** [comment]
Temporal functionality will be rewritten for v2, this will be added to the list of features.

**Comment by emlynwest** [comment]
A thought just occurs. What do you mean by "first" as the current revision will always be the "first"?

**Comment by sagikazarmark** [comment]
I mean first to be the first revision, and last to be the current revision, which makes no sense, as null can be used now to get the current revision in this function. So probably the "first" is the only which makes sense.

**Comment by emlynwest** [comment]
That makes more sense. I'll make sure it's included in v2 temporal.
