### ISSUE TITLE
Just added ORM slug separator feature

### ISSUE THREAD

**Issue by sagikazarmark** [fuel/orm#324]
I am not really familiar with regular expressions (I know, it is a shame :smiley: ), but I think in Observer Slug on line 107 the line should be changed from

``` php
if (preg_match('/^'.$slug.'(?:-([0-9]+))?$/', $record->{$this->_property}, $matches))
```

to

``` php
if (preg_match('/^'.$slug.'(?:' . $this->_separator . '([0-9]+))?$/', $record->{$this->_property}, $matches))
```

Now checking for the same slug is broken, it always tries to insert slug_1. I didn't PR, as I am not sure.

**Comment by WanWizard** [comment]
That is correct, the regex should change as well.

**Comment by sagikazarmark** [comment]
Is the replacement code above correct? Because I commit it then.

**Comment by WanWizard** [comment]
Well, that depends. 

Problem is that if you pick a separator that has special meaning in a regex (like for example a plus sign, or a dot), it has to be escaped. If you don't, it will break the regex.

**Comment by sagikazarmark** [comment]
How should this be solved than? As I said, regex is not my best friend.

**Comment by WanWizard** [comment]
Now that is the million dollar question! :grin: 

@FrenkyNet, any suggestions? Check against the list of characters-to-escape-in-a-regex?

**Comment by sagikazarmark** [comment]
``` php
$separator = (preg_match('/\.|\^|\$|\*|\+|\?|\(|\)|\[|\{|\\\\|\|/', $this->_separator) ? '\\' : '') . $this->_separator;
```

Is it a possible solution? It works for me.

**Comment by sagikazarmark** [comment]
Also I think limiting the separator char to one char is a good idea. Actually the solution above assumes that it is only one char.

**Comment by sagikazarmark** [comment]
I found the answer to the regex char thing, but there is another thing that makes it useless: Inflector only lets us use underscore or dash. This means that no other char can be used than - or _ (with the current implementation).

How should we proceed? Is it the limitation then or do something with Inflector (which might break thing, as anyone who used a star in Inflector and got a dash instead would get a star). I've also talked with @stevewest about multiple chars as a separator. This could be OK in Slug observer, but not in Inflector.

**Comment by WanWizard** [comment]
I'm not sure why Inflector::friendly_title() would limit the separator you can choose. I also find some of the replace decisions odd. If you don't allow non-ascii, but pass something with a lot of non-ascii, you end up with a long string of dashes?

**Comment by WanWizard** [comment]
And why limit the separator to a single character? @stevewest ? I don't see a reason for that, what separator is acceptable depends on the use of the method inside the application.

**Comment by emlynwest** [comment]
IMO we need to keep the ability to an unlimited number of characters to not risk breaking BC. Looking at `Inflector::friendly_title()` it seems that it can only handle underscores or hyphens.

https://github.com/fuel/core/blob/1.8/develop/classes/inflector.php#L251

**Comment by WanWizard** [comment]
Yes, that is why I commented that for me it's an application descision what separator is acceptable, the framework should not limit the users choice if there is no reason.

**Comment by emlynwest** [comment]
I totally agree with that, just stating the current `Inflector` behaviour does not support that

**Comment by WanWizard** [comment]
Ok. @FrenkyNet, you know of any reason why Inflector::friendly_title() is limited hardcoded to dash and underscore as possible separators? If not, I'll remove the limitation.

**Comment by sagikazarmark** [comment]
@WanWizard any update on this?
