### ISSUE TITLE
Custom data array when using ORM model with DB->as_object()

### ISSUE THREAD

**Issue by julesjanssen** [fuel/orm#334]
See http://fuelphp.com/forums/discussion/comment/16780#Comment_16780

> With ORM 1.7/master, passing an ORM model to the DB as_object method would put columns that are not properties of the model in the _custom_data array.
> Since updating to 1.8/develop, those extra columns just disappear. Any idea how this can be fixed?

The Model I'm using has no EAV container defined. Just a simple \Orm\Model extending model which worked perfectly with 1.7/master.

**Comment by WanWizard** [comment]
Is this still an issue? As far as I can see in the code any values passed that are not defined properties are moved into the custom data store.

**Comment by julesjanssen** [comment]
Looks like this issue isn't resolved yet. Here's an example

``` php
\DB::select_array(array(
                'e.id',
                'e.title',
                'e.description',
                'e.extradata',
            ))
            ->from(array('example', 'e'))
            ->where('e.id', '=', 1)
            ->as_object('\Model_Example')
            ->execute()
            ->current();
```

The Model_Example model has 3 defined properties:
- id
- title
- description

I'm expecting the `extradata` result in `_custom_data`, but it's simply being ignored.
Simply switching to the 1.7/master ORM branch resolves the issue. Any idea?

**Comment by WanWizard** [comment]
First reaction would be "your model properties are not defined correctly". But I assume this is just an example to prove your use-case?

**Comment by julesjanssen** [comment]
It was indeed. Thanks for the quick update.

**Comment by WanWizard** [comment]
Thanks for the feedback
