### ISSUE TITLE
register_observer only works if both arguments are present

### ISSUE THREAD

**Issue by n00b32** [fuel/orm#341]
```
            static::register_observer('Observer_Cacher');
```

causes the ::observers() method to return 'array(0=>cacher)'; and it tries to load calss '0'

```
            static::register_observer('Observer_Cacher', array());
```

works, because it sets ::observers() to 'array(cacher=>0)' which is correct :)

**Comment by WanWizard** [comment]
Why is that correct?

If I look at the observe() method that uses this data, it expects `$observer => $options`, and treats `$options` as an array.

So I think it should be `array('cacher' => array() )`...

**Comment by WanWizard** [comment]
I think this will do:

``` php
    public static function register_observer($name, $options = array())
    {
        $class = get_called_class();
        static::$_observers_cached[$class] = static::observers() + array($name => $options);
    }
```

Can you test that, I'm not in a position to do so atm...

**Comment by WanWizard** [comment]
Implemented like this: https://github.com/fuel/orm/commit/c7bd709d79b0690297c8f3f33c95270445051eb6
