### ISSUE TITLE
Direct access of relational objects fails with Model_Temporal

### ISSUE THREAD

**Issue by thiver** [fuel/orm#347]
With Orm\Model I could fetch all related object and its properties by the defined relation name.

```
$object  = Model_Object::query()->get_one();

$object->relation_name => related object or iterator of related objects
$object->relation_name->property => direct access to property of related object
```

With Orm\Model_Temporal I can't fetch the related objects anymore and I have to use a seperate query to retrieve the related objects.

For testing the problem I created an empty FuelPHP 1.7.1 project and activated the ORM package. This is wat happened:

I created 2 models, a model "Session" and a model "Presentation":

```
<?php

class Model_Session extends Orm\Model_Temporal
{
    protected static $_primary_key = array('id','temporal_start','temporal_end');


    protected static $_temporal = array(
        'start_column' => 'temporal_start',
        'end_column' => 'temporal_end',
        'mysql_timestamp' => true,
    );

    protected static $_table_name = 'sessions';

    public static $_properties = array(
        'id',
        'temporal_start',
        'temporal_end',
        'title',
    );

    protected static $_has_many = array('presentations');
}


<?php

class Model_Presentation extends Orm\Model_Temporal
{
    protected static $_primary_key = array('id','temporal_start','temporal_end');


    protected static $_temporal = array(
        'start_column' => 'temporal_start',
        'end_column' => 'temporal_end',
        'mysql_timestamp' => true,
    );

    protected static $_table_name = 'presentations';

    public static $_properties = array(
        'id',
        'temporal_start',
        'temporal_end',
        'title',
        'session_id',
    );

    public static $_belongs_to = array('session');
}
```

Every session can have multiple presentations (one-to-many).
Every presentation can have only one session (many-to-one).

I executed the following code in a controller:

```
    $session = new Model_Session();
        $session->title = "Session";
        $session->save();
        $presentation = new Model_Presentation();
        $presentation->title = "Presentation";
        $presentation->session = $session;
        $presentation->save();

        $fetched_presentation = Model_Presentation::query()->get_one();
        var_dump($fetched_presentation->session);
```

Each action call:

Creates a new Session object
Creates a new Presentation object with the Session as relation.
Fetches a Presentation out of the database and dumps the session relation.
First call, the database is empty:

Successful generation of the 2 objects and the var_dump is not empty.

All calls when the database is not empty anymore:

Successful generation of the 2 objects, but the var_dump stays NULL all the time

Any solutions? Tested it on 1.8/develop yesterday and I had the same issue.

**Comment by emlynwest** [comment]
What happens if you do the `$fetched_presentation = Model_Presentation::query()->get_one();` in a separate request from the initial create. The way that Temporal works internally can sometimes be a little funny with the ORM's model caching.

**Comment by thiver** [comment]
If I just do a fetch without creating objects, I still get a NULL object as the relationship.

**Comment by emlynwest** [comment]
It looks like a problem with lazy loading. Try eager loading the relation.

**Comment by thiver** [comment]
Eager loading works on 1.8/develop! Thx
