### ISSUE TITLE
Clear Cache function

### ISSUE THREAD

**Issue by dercoder** [fuel/orm#348]
I have found this: https://github.com/fuel/orm/pull/194 but this function has been removed

It would be nice to have a function to clear the cache. For Example i have created a socket client to import data into my database using ORM Models. This Data always changes (New Models) so the Cache is getting bigger and bigger.

So it would be nice to have such function:

```
$model = Model_Test::find(123);
$model->name = 'New Name';
$model->save();

# For Example to remove this model data from cache
# Maybe you will find a better method name
$model->purge(); 
```

**Comment by emlynwest** [comment]
For now you can implement this functionality yourself or use the `->from_cache(false)` functionality. No new functionality for the orm will be added for v1. v2 will have a totally new architecture so doing this sort of thing will be easily possible.

**Comment by dercoder** [comment]
Ok, but i cant work with `->from_cache(false)` because this will always load the data from database and this will decrease performance of my socket client.

Is there any release date for v2?

**Comment by emlynwest** [comment]
If performance is you concern then do not use the ORM as model hydration adds considerable overhead.

There is currently no release date for v2. Work on the new orm has started but is slow at the moment. I am expecting this to pick up soon though.

**Comment by dercoder** [comment]
Thx 4 Infos. It would be nice if the new ORM also work with MongoDB ;)

**Comment by emlynwest** [comment]
If the v2 database package supports it (https://github.com/fuelphp/database) then it will. But seeing that MongoDB is not intended as use as a RDBMD it does not seem likely.

**Comment by dercoder** [comment]
I understand. But why you dont use something like Doctrine?

**Comment by WanWizard** [comment]
My guess is that by asking that question, you have never actually used it?

**Comment by dercoder** [comment]
Thats correct :)

**Comment by WanWizard** [comment]
Then by all means, do. And you'll never ask that question again. ;) 

I can give you a few keywords as pointers: slow, complex, time consuming.

**Comment by WanWizard** [comment]
But that shouldn't stop you, you can use doctrine without problems in any Fuel app. Just add it to the composer.json and run an update.

**Comment by dercoder** [comment]
Ok, thx for your help and informations

**Comment by egold** [comment]
Yeah I noticed the unfortunate caching of Model tracking down a difficult bug myself. I have a supervisord-managed worker process that is long-running and does work off a beanstalkd queue. It turns out this unconfigurable cache keeps filling, and the data is stale. There's no purge, there's no flushing logic, and there's no max memory config. 

It makes sense in the context of a single web request, but for long-running oil tasks, it's pretty hard to use the model layer. I hope v2 either defaults it to "off" (good), allows it to be configured (better), or simply leaves caching up to the developer (best).

**Comment by emlynwest** [comment]
v2 will have model caching enabled by default (like v1) but it will me much easier to turn it off or switch it out for another method of caching.

**Comment by WanWizard** [comment]
This has been addressed in https://github.com/fuel/orm/commit/989dc0701ba30c9540b969c25e9080e0fa51b054
