### ISSUE TITLE
Orm\Exception [ Error ]: Primary key cannot be changed.

### ISSUE THREAD

**Issue by WanWizard** [fuel/orm#35]
All of a sudden I get this error when I'm trying to call the save() method on creating a new record (plain and simple, no relations).

Backtrace;
1. PKGPATH/orm/classes/model.php @ line 817
2. PKGPATH/orm/classes/model.php @ line 763

The code in my app hasn't changed for weeks, I only update fuel (develop) once every few days. The code is up to date as of 30min ago.

**Comment by WanWizard** [comment]
I assume reset() will fail as well, as it also tries to assign values to properties (which I assume contains the primary key)

**Comment by jschreuder** [comment]
Not sure why it popped up now, but this should solve it.
