### ISSUE TITLE
and_where_open / and_where_close broken?

### ISSUE THREAD

**Issue by thiver** [fuel/orm#358]
In FuelPHP 1.7.2 it seems like and_where_open/and_where_close don't set the parentheses anymore in a query?

**Comment by thiver** [comment]
(Model_Temporal is being used.)

**Comment by emlynwest** [comment]
Because Model_Temporal adds extra where queries you sometimes need to build your query in a different way to make things work. You can use `DB::last_query()` to see what it is running, this is unfortunatly a side effect of using Temporal.

**Comment by thiver** [comment]
Issue resolved, there was a method override that did bad things, my bad.
