### ISSUE TITLE
[BUG] New commits from today cause ORM related results to flip

### ISSUE THREAD

**Issue by rickmacgillis** [fuel/orm#367]
The best way for me to explain this issue is with an example.

**Steps to reproduce**
1. Create two models in a has-many relationship structure. In the following example, I'm relating WordPress tables with each other to select post meta for each post.
2. Run the following code.

```
$model_posts = \Model\Posts::forge();
$posts = $model_posts::query()
    ->related('postmeta')
    ->where('postmeta.meta_key', '_thumbnail_id')
    ->where('post_status', 'publish')
    ->where('post_type', 'post')
    ->get();
\Debug::dump($posts);
```

**The issue**
The new code is not reverse-compatible with older versions of the 1.8/develop source code. Before the latest commits, `$posts` would contain `\Model\Posts` objects in an array, one for each row. After the latest commits, `$posts` now contains an array of instances of the related object for each row.

**Comment by WanWizard** [comment]
Merge reverted: https://github.com/fuel/orm/commit/60cc4eb576c5378ce1c517ace672ecaf21cc140a
