### ISSUE TITLE
"find" method throws Fatal Error

### ISSUE THREAD

**Issue by nickautomatic** [fuel/orm#375]
On the 1.8/develop branch, calling `find('all')` (and other similar `find` methods) throws a Fatal Error ("Cannot access protected property Orm\Query::$alias") from commit [122b49ba24e97](https://github.com/fuel/orm/commit/122b49ba24e979648c1deea8af8430aeaf31c520) onwards.

This happens on, eg. the default "index" method on a scaffolded controller.

I'm using PHP 5.3.27 / Apache 2.2.26.

**Comment by WanWizard** [comment]
I can not reproduce this, find('all') works fine here. 

Using the current 1.8/develop, PHP 5.6.7.

**Comment by emlynwest** [comment]
I can't reproduce this either. I would imagine that others would have reported this problem if it where an actual bug, seeing that it's dealing with `Model::find()`

**Comment by WanWizard** [comment]
Please double check if both your Fuel/Core and all core packages (like ORM) are either all on 1.7.2 or on 1.8/develop, and not a mix? 

And if on 1.8/develop, make sure it's up to date. I can remember this error message, but it was fixed very soon, I think in the commits of March 4th.
