### ISSUE TITLE
Condition in query relation generate a WHERE

### ISSUE THREAD

**Issue by AdamSGit** [fuel/orm#390]
When you put a condition in a query relation, it generate a WHERE clause in the main query instead of an ON clause
(Fuel 1.8, on both has_one and has_many relation)
Link to the forum post about it : 
http://fuelphp.com/forums/discussion/13815/condition-in-relation-and-empty-result

**Comment by WanWizard** [comment]
This is about adding the condition to `related()`..

The same condition, when defined on the relation itself (in the model property) does end up in the correct place.

**Comment by WanWizard** [comment]
No further info received.
