### ISSUE TITLE
Use orm without framework

### ISSUE THREAD

**Issue by quevlu** [fuel/orm#410]
Hi guys,

I have a question, Can i use ORM fuel without framework ? if it's possible how can i install it ?

Thanks!

**Comment by stvowi** [comment]
Yes of course...with composer: https://packagist.org/packages/fuel/orm

**Comment by quevlu** [comment]
Thank you so much and i have a more question. How can i install it ? Do you have a sample code ?

**Comment by stvowi** [comment]
Please study this [website ](https://getcomposer.org/) or watch [youtube ](https://www.youtube.com/watch?v=I6wm15OWyqg) to get an inspiration.

**Comment by WanWizard** [comment]
You can't really, the ORM builds on top of the DBA layer from the framework, so you need that handy somewhere. And there are probably other core class dependencies too.

**Comment by ghost** [comment]
I need use orm\fuel in my project without framework, I need a simple tutorial how integrate it in my project if possible. Thank you !
I have installed with composer but I don't know how I can use it in my code for integrating in my project

**Comment by WanWizard** [comment]
See my previous response. It is tied in with the framework.

**Comment by ghost** [comment]
If I understand correctly I can not use \fuel\orm outside its framework (framework fuelphp)...
And do not you know another orm that goes in the same concepts as \fuel\orm ?
Please help me because I build a mini framework made home !

**Comment by WanWizard** [comment]
The best framework independent ORM is Doctrine. But it is quite complex to use. You could also look at Propel, or less known ORM's like "Spot ORM". Or something like LessQL. And Google can probably find others too.

**Comment by ghost** [comment]
I hesitate between nextras orm and phpdatamapper

**Comment by ghost** [comment]
Thank

**Comment by WanWizard** [comment]
I don't know either of them.

**Comment by stvowi** [comment]
If you don't need a tank than try out https://redbeanphp.com/index.php

**Comment by stvowi** [comment]
or https://medoo.in/ with a [model class](https://packagist.org/packages/awheel/medoo-model)

**Comment by ghost** [comment]
I am thinking of building my own homemade orm, being the simplest while taking inspiration from \orm\fuel on the creation of models and CRUD.
Thank you all the same

**Comment by ghost** [comment]
Thanks for the advice, I find that Medoo is very simple and easy to set up !
