### ISSUE TITLE
Problem with order of executing query in observer

### ISSUE THREAD

**Issue by huuphuc2401** [fuel/orm#411]
I have an Model_M with 2 observers:
- Observer `A` use Model_Log to write logs when Model_M changed ()
- Observer `B` calculate something base on logs

I add Observer `A` and `B` to Model_M with order: `A` first and `B` later.

I debug in php and see that the process `write log` is run first and `calculating` is run later

## Expected result
`calculating` process can find the log

## Result 
`calculate` process can not find the log **(I checked in Profiling, the
sql query of `calculating` is executed before the sql query of `write log`)**

**Comment by WanWizard** [comment]
The query is executed when you say it has to be executed, so when you call save() on the object. 

You'll have to debug further, perhaps observers on related models that interfere? You can use `Debug::backtrace()` to output the call path if you want to see how you got to a certain place in the code.

**Comment by huuphuc2401** [comment]
@WanWizard I used `Debug::backtrace()` and found problem (observers on related models as you said). Thank you so much.

**Comment by WanWizard** [comment]
You're welcome.
