### ISSUE TITLE
get_diff method does not work in event after_update of observer (fuel/orm version 1.8.0.1)

### ISSUE THREAD

**Issue by huuphuc2401** [fuel/orm#412]
I have `Model_Product` with property `name`

I add an observer `Observer_Name` to check `name` changed to model `Model_Product`
```php
// fuel/app/classes/model/product.php
class Model_Product extends \Orm\Model
{
	protected static $_table_name = 'product';
	protected static $_properties = array(
		'id',
		'name',
		'price',
		'created_at',
		'updated_at',
	);
	protected static $_observers = array(
		'Orm\Observer_CreatedAt' => array(
			'events'          => array('before_insert'),
			'mysql_timestamp' => false,
		),
		'Orm\Observer_UpdatedAt' => array(
			'events'          => array('before_update'),
			'mysql_timestamp' => false,
		),
		'\\Observer_Name' => array('events' => array('after_update')),
	);
}
```

```php
// fuel/app/classes/observer/name.php
class Observer_Name extends \Orm\Observer
{
	public function after_update(\Orm\Model $model)
	{
		var_dump($model->get_diff());
	}
}
```

Update name
```php
$product = Model_Product::find(1);
$product->name = 'new name';
$product->save();
```

## Expected result

`var_dump` display the diff of `new name` and `old name`

## Result

`var_dump`  display 2 empty arrays

## More information
- Environments: CENTOS 7, Apache 2.4.6, PHP 5.4.16
- I set in composer.json `"fuel/orm":"1.8.*"`. `fuel/orm` version 1.8.0.1 is downloaded. Then I got this problem
- If I set `"fuel/orm":"1.8.0"` in composer.json, it work well (display the diff). The old version 1.7 work well too.

**Comment by WanWizard** [comment]
Thanks for reporting this. I can confirm this is still an issue with 1.9/develop.

**Comment by WanWizard** [comment]
Looked at the logic.

This behaviour is correct. The "after_update" observer is called AFTER the update has been completely processed. At this point, the object isn't in altered state anymore, it's state refects the data in the database, so there is no diff between the data in the object, and the data in the database.

Want you need is the "before_save" event, which gives you the state of the object before any save operation is executed, including any observers. You can also use "before_update", but that also gives you any changes made by observers (such as CreatedAt/UpdatedAt, depending on the order the observers are defined in).

The change made in 1.8.0.1 was a bug fix, to correct incorrect behaviour in previous versions.
