### ISSUE TITLE
Update at branch 1.8/master should be released

### ISSUE THREAD

**Issue by ppatrik** [fuel/orm#419]
There are updated sources with commit number 7891ba39622de64bf3a08352fcea758bd8f45284 without we cannot use Model_Temporal. Thanks for making release tag.

**Comment by WanWizard** [comment]
There is a new minor release pending, which will address this.

**Comment by ppatrik** [comment]
Thanks.
I'm just adding information from FuelPHP Forums: https://fuelphp.com/forums/discussion/13902/hydrate-error-with-model_temporal.
Minor release is planed: probably sometime next week.

**Comment by WanWizard** [comment]
Has been delayed a bit due to personal circumstances, it will probably be beginning of February.

**Comment by ppatrik** [comment]
Thank, no problem :).
