### ISSUE TITLE
[Bug report]I will report this bug in fuelPHP forum

### ISSUE THREAD

**Issue by allgrowsm** [fuel/orm#429]
Because fuelphp forum dose not allow me to upload files, I will report this bug in the forum.

[query_new.zip](https://github.com/fuel/orm/files/4985528/query_new.zip)

**Comment by allgrowsm** [comment]
Here is link for forum that I post.

https://fuelphp.com/forums/discussion/15290/bug-reporti-could-not-get-related-data-using-orm#Item_2

**Comment by WanWizard** [comment]
Did you manage to test if the latest fixes to the ORM adressed your issue?

**Comment by allgrowsm** [comment]
@WanWizard @AdamSGit @ysshir 
Hello there,
Yes, all related data is fetched and saved properly.
Thank you very much for fixing it :)
