### ISSUE TITLE
The solution for Issue #432  seems to be wrong.

### ISSUE THREAD

**Issue by mt-u** [fuel/orm#443]
Due to this code fix(Issue #432, [commit](https://github.com/fuel/orm/pull/432/commits/491f2b5af5f2bd2b16fe0f04c0c30d5cb56aa0ab)), the alias with `DB :: expr('sum(value)')`, on the other hand, now gives an error.
The code before it is modified works fine.
I want you to revert to the previous code.

**Comment by ysshir** [comment]
@mt-u
you are right, I was wrong. so sorry...

@WanWizard 
I know you are so busy, but please review my PR https://github.com/fuel/orm/pull/448
thanks
