### ISSUE TITLE
Doesn't save related models when multiple relations are created

### ISSUE THREAD

**Issue by phil-lavin** [fuel/orm#45]
I have some code which takes an instance of Model_Subscriber ($sub) and creates an instance of Model_List ($list) under $sub->lists - e.g. $sub->lists[] = $list;

The code then adds a few instances of Model_SubscriberField to $sub->fields

Following this, I call a save() on $sub.

This results in the Subscriber being inserted into the right table. It also results in the data from the instances of Model_SubscriberField in $sub->fields being inserted into the right table. However... the new instance of Model_List from $sub->lists is not inserted.

If I call save() on $sub directly after adding the list to $sub->lists and again after adding the fields to $sub->fields this works as expected. I have also checked that $sub->lists has not been modified between when I add to it and when I call save().

Is it by design that save() on $sub will not save multiple relations and as such, does this need documenting; or is this a bug?

The code is built as a package and I can provide this if the answer/solution is not obvious.

**Comment by jschreuder** [comment]
I get what you're saying, but I need the code examples to be able to see if I can replicate the issue.

**Comment by phil-lavin** [comment]
No problem - give me a few mins to get them together.

**Comment by phil-lavin** [comment]
I have put the package in a simple example set up of the latest git develop release. Getting it to run should be as simple as importing mailing_lists.sql into a database and configuring the PhilLavin\Subscriber\Subscriber::DB part of the array in app/config/db.php to point to it.

action_index() of Controller_Welcome does an example subscriber creation in list #2 (already in the DB dump) with some field data.

http://127dot0dot0dot1.com/test.zip

**Comment by phil-lavin** [comment]
Looked into this. The cause is this line in __get() of Orm\Model...

$this->_update_original_relations();

When you do "$modelinstance->relationname[] = Model_Foo::find(...)" this makes a call to __get() and thus the original relations are updated. This prevents them saving properly as they are passed through to save() in Orm\ManyMany.

We cannot see the logic of when you would want to update the original relations when you do a get so we haven't submitted a fix removing it - but our inclination is that it's not required.

Thanks

**Comment by jschreuder** [comment]
Ahh, now I get it. The problem is that after a lazy-load the lazy-loaded relation needs to be added to the originals in order to be able to detect a change in them. The `_update_original_relations()` shouldn't update all, but just that specific relationship in this case. We should be able to solve this by adding a param to `_update_original_relations()` that allows you to pass an array of specific relations to update (in the case of `__get()` just the lazy loaded relation).

**Comment by jschreuder** [comment]
I don't have time to fully test this, but I think this should solve it. Could you let me know if it does?

**Comment by phil-lavin** [comment]
Bastard. Just wrote that and was going to submit a patch ;)

Thanks for the fix. I'll test your implementation now.

**Comment by phil-lavin** [comment]
Yarp - that's working. Thanks :)
