### ISSUE TITLE
Second-degree relations not being eager-loaded

### ISSUE THREAD

**Issue by romosan** [fuel/orm#450]
At least since the commit 8483d217f402a39ecc06ebd8d4a771194edd9f29 (_rewritten object hydration_), second-degree relations don't seem to work propely. I am referring to something like `['related' => 'first.second']` where, in my case, `first` is a `has_many` relation and `second` a `belongs_to` relation.

This could be the same problem as #439 but I have opened a new issue because the old one is closed and the code has since changed. Judging by the current code, the second-degree relation gets added to the first-degree relations list, instead of a particular record. In `\Orm\Query::process_row`:

```php
				// store it, but do not overwrite an existing result!
				if ($model['singular'] === true)
				{
					if ( ! array_key_exists($current, $pointers[$parent]))
					{
						$pointers[$parent][$current] = $record;
					}
```

Should be perhaps something like:

```php
				// store it, but do not overwrite an existing result!
				if ($model['singular'] === true)
				{
					if ( ! array_key_exists($current, $pointers[$parent][$parent_pk]))
					{
						$pointers[$parent][$parent_pk][$current] = $record;
					}
```

But please note that `$parent_pk` is not defined and I am not sure how it should be and whether that would be enough.

**Comment by WanWizard** [comment]
I assume you have tested this using the 1.9-dev code?

**Comment by romosan** [comment]
Yes, latest version and various versions in-between.

**Comment by WanWizard** [comment]
Ok, I'll do some debugging, haven't bumped into this issue myself.

**Comment by WanWizard** [comment]
I've tested relations of different types, to 4 deep (so "A.B.C" on the root object). 

Let me know if this addresses your issue too.

**Comment by romosan** [comment]
Yes, it does!

**Comment by WanWizard** [comment]
Thanks for the feedback.
