### ISSUE TITLE
LIMIT after ORDER in query

### ISSUE THREAD

**Issue by patie** [fuel/orm#46]
cannot be limit located on end of sql ? because when i order-ing along joined table (with limit) = its ordering only limited part mean data are first limited aned next ordered..this is not desirable - at least for me

i think this should be right - ordering all data and after that limit all data to some rows

what you mean about this ? thanks

**Comment by jschreuder** [comment]
It's a compromise that works best in most cases, if you know a better way I'm open to suggestions. Thus for now I don't see an issue or bug here, discussion should go on the forums.

**Comment by patie** [comment]
when will be changes as i say - you result dont be changed, but its solution for ordered joined rows with limiting.. only what it need is move limiting to end of query if its not too complicated ... sorry for bad english I can not explain it well thanks for your time

**Comment by jschreuder** [comment]
It's only "not too complicated" if you think an ORM is easy. I'm open to suggestions, but only to the whole system not for specific parts that are the result of a greater compromise. It's not possible to change that without changing the whole thing which will have far greater complications.

**Comment by ushis** [comment]
What about the new method max_rows()? You wrote something about here: http://fuelphp.com/forums/topics/view/3239/10#4522
