### ISSUE TITLE
data_type => 'boolean' needs special handling.

### ISSUE THREAD

**Issue by jeffutter** [fuel/orm#49]
We need some special handling when saving fields that have data_type => boolean (particularly if null is not allowed);

If i create a model with 3 boolean fields and then set them like

```
$model = new My_Model::factory();
$model->boolean1 = 1;
$model->boolean2 = 2;
$model->save(); // this will fail as no value has been defined for boolean3
```

The above behavior may be acceptable, but the place where this is an issue is when also using the Typing Observer and doing something like this:

```
$model = new My_Model::factory();
$model->boolean1 = 1;
$model->boolean2 = 1;
$model->boolean3 = 0;
$model->save(); // this works
$model->unrelated_property = 'foo';
$model->save(); // This will fail saying that boolean3 is required.
```

With Typing ORM sets those fields to type boolean (which is should) but boolean false = doesn't exist, so when ORM tries to save those fields it skips over them resulting in an error if they are required.

Easiest solution in can think of is check all fields's data_types before saving and if they are boolean, set them to 1 if they have some value or 0 if they dont.

**Comment by jschreuder** [comment]
Easiest solution already exists: give it a default value and set the values to 0 and 1 when setting them. Or use the typing observer if you don't want to add it yourself. Boolean is a fake fieldtype which you should deal with as a tinyint(1) or use the typing observer.

**Comment by jeffutter** [comment]
I was going to insist that I was using Typing so I couldn't figure out why this was happening. Then i realized I was loading the typing observer AFTER validation, thus it failed. I didn't realize order mattered. Thanks for pointing me in the right direction
