### ISSUE TITLE
With the Validation oberver, can't have multiple objects of same type.

### ISSUE THREAD

**Issue by jeffutter** [fuel/orm#50]
If you have multiple objects of the same type in a file, while that object uses the Validation Observer you get errors like:

```
<strong>Notice:</strong> Field with this name exists already, cannot be overwritten through add(). in PKGPATH/orm/classes/observer/validation.php [43]: add
```

Example how to produce error:

```
$model1 = My_Model::factory(array(...));
$model1->save();

$model2 = My_Model::factory(array(....));
$model2->save();
```

This is caused by Observer\Validation creating it's Fieldset named after the Model's Class. Therefore when you have 2 of the same type of models it ends up using the same Fieldset Instance causing things to muck up.

**Comment by jschreuder** [comment]
This is related to issue #59, closing this one in favor of that one.
