### ISSUE TITLE
Saving existing model fails when finding the same object, probably because of caching

### ISSUE THREAD

**Issue by Arjeno** [fuel/orm#55]
$user = Model_User::find_by_email("original@email.com");
echo 'Email: '.$user->email; echo '<br />';
echo 'User changed: '.$user->is_changed() ? 'true' : 'false'; echo '<br />';
$user->email = "different@email.com";
echo 'Email: '.$user->email; echo '<br />';
echo 'User changed: '.$user->is_changed() ? 'true' : 'false'; echo '<br />';

$user2 = Model_User::find_by_email("original@email.com");
echo 'Email: '.$user2->email; echo '<br />';
echo 'User2 changed: '.$user2->is_changed() ? 'true' : 'false'; echo '<br />';

$user->save();

Results in:

Email: original@email.com
true
Email: different@email.com
true
Email: different@email.com
true

But the record is not saved. Further investigation reveals that the 2nd object comes from cache and probably resets the original values. Thus not detecting any changes and not saving.

**Comment by jschreuder** [comment]
Your bugreport seems faulty in 2 ways:
1. Under the first Email: original@email.com it should say false, why it says true is beyond me.
2. Reloading an object caused its original values to be reset in earlier versions not the actual values, now it's just ignored. (are you on RC3?)

You are right, the object isn't created a second time during runtime. It never should, each unique object should be unique and not be in there twice.

**Comment by Arjeno** [comment]
Yes I am on RC3. The bug got my attention because I am using a slugify observer which checks if the slug is unique in the database (called on before_save). For some reason it resets the original values of the user object and my properties aren't saved.

**Comment by jschreuder** [comment]
Could you verify if this is still true with the latest pull from develop? I have tried to verify this and could not replicate the issue, also your report seems faulty and you didn't explain some of the oddities I pointed out. If this isn't verified within 2 days I'm closing the issue as invalid.

**Comment by jschreuder** [comment]
As you haven't been able to give me verification of this issue I'm going to have to assume it's invalid.
