### ISSUE TITLE
Support the REST controller

### ISSUE THREAD

**Issue by Naatan** [fuel/orm#57]
Currently when you run a query that results in an array with multiple model entries and send the results to REST it will just result in an array with empty entries.

A simple way to remedy this is to make all the properties of each result set public properties, that way when json_encode runs through it it will properly be converted to a JSON object.

**Comment by philsturgeon** [comment]
You can use $foo->to_array() to give yourself plain data and not a full ORM object. I wouldnt like to infect the REST controller with ORM logic as why should it? ORM is a package that may or may not be used, just like Mongo ODM may or may not be used.

**Comment by jschreuder** [comment]
This isn't really an issue with the ORM. This is an issue with how ArrayAccess objects are handled in the REST Controller/Format class, those should always be turned into arrays before output. I recently had a discussion relating to this about the Format class for which I have a fix almost ready to go: https://github.com/fuel/core/commit/fb5c5494ee4d62f216ce42cc758e2dcfb5e5a308#commitcomment-469871
