### ISSUE TITLE
Many_Many doesn't Delete

### ISSUE THREAD

**Issue by phil-lavin** [fuel/orm#64]
``` php
$code->free_products = array();

foreach (\Input::post('free_products', array()) as $id) {
    if (($obj = \Model_Product::find($id)))
        $code->free_products[] = $obj;
}
```

The expected behaviour of the above code would be that relations which are no longer in $code->free_products would be deleted. This does not happen.

**Comment by phil-lavin** [comment]
This has to do with the fact that $original_model_ids as passed through to Many_Many save() is null.

**Comment by phil-lavin** [comment]
Fixed like this:

``` php
$code->free_products;
$code->free_products = array();

foreach (\Input::post('free_products', array()) as $id) {
    if (($obj = \Model_Product::find($id)))
        $code->free_products[] = $obj;
}
```

It seems that basically you have to make a __get call to hydrate the object before you change it. Suggested fix would be to populate the original relations on __set like it is on __get.

**Comment by dhrrgn** [comment]
@jschreuder: Is this still an issue...don't know this code to well.

**Comment by jschreuder** [comment]
@dhorrigan still have to look into this, will probably have to wait till the weekend.

**Comment by jschreuder** [comment]
Tested with the exact same setup, can't replicate and remember fixing something similar earlier. Closing this, reply if you still experience this problem.

**Comment by phil-lavin** [comment]
Finally got around to testing this on latest 1.1/develop and the issue is still apparent. I set up a new project with a simple many to many relationship (between people and jobs).

This doesn't work:

``` php
<?php
$phil = \Model_Person::find()->where('name', 'Phil')->get_one();

$phil->jobs = array();
$phil->jobs[] = \Model_Job::forge(array('name'=>'Hummm'));

$phil->save();
?>
```

This works:

``` php
<?php
$phil = \Model_Person::find()->where('name', 'Phil')->get_one();

$phil->jobs;
$phil->jobs = array();
$phil->jobs[] = \Model_Job::forge(array('name'=>'Hummm'));

$phil->save();
?>
```

**Comment by WanWizard** [comment]
Reopened on request of Phil Lavin.

**Comment by WanWizard** [comment]
Just tried:

```
    // relate person 2 to Job 1 and Job 2
    $person = Model_Person::find(1);
    $person->job = array(
        Model_Job::find(1),
        Model_Job::find(2),
    );
    $person->save();

    // delete the related records, and assign job 3
    $person->job = array(
        Model_Job::find(3),
    );
    $person->save();

    // delete the related records, and assign new job 4
    $person->job = array(
        Model_Job::forge(array('name' => 'Job 4')),
    );
    $person->save();

    // delete the related records, and assign new job 5
    $person->job = array();
    $person->job[] = Model_Job::forge(array('name' => 'Job 5'));
    $person->save();
```

And this all works. So I consider this case closed.

**Comment by phil-lavin** [comment]
Yeh, that will work. The issue is because, when a model is loaded with find(), the relations aren't loaded. This is, obviously, deliberate and relations are only loaded when they are accessed. They are, however, not loaded when they are set. This means that the original relations array is not populated and thus overwritten data is not deleted.

See my above example.

The workaround is to either load related data with ->related(), or lazily, if you want old data to delete.

**Comment by WanWizard** [comment]
So your saying that find(1) works, but find()->where('id', '=', 1)->get_one() doesn't?

**Comment by phil-lavin** [comment]
No. It's an issue when related data already exists. In your example, you do the find(1) at the top and then add data to it, save the data, edit the data and then re-save it. If the data existed to begin with, it wouldn't be deleted.

**Comment by WanWizard** [comment]
ok, I understand now. Back to the tests...

**Comment by WanWizard** [comment]
@phil-lavin could you see if this fixes it for you? (don't know why a reference would close an issue...)

**Comment by WanWizard** [comment]
@phil-lavin came up with a new solution to track a reset of relations in your use case. Could you test it please?

**Comment by andrewwheal** [comment]
@WanWizard just tested this with the below and it seems to be working great

```
    $widget = Model_Widget::find(1);
    $widget->categories = array(Model_Category::forge(array('name' => 'Cat3')));
    $widget->save();
```

**Comment by WanWizard** [comment]
It has an issue atm, it doesn't update the object cache.

So if you have objects in the ORM cache that are 'unlinked' by this operation, the record in the database will have it's foreign key reset to NULL, but the object in cache still has the foreign key value.

We're looking into a solution for this issue, but it might be a few weeks due to time constraints.

**Comment by WanWizard** [comment]
I'm not sure where this concern comes from. This is about manymany, in which the FK's ar in the through table, which isn't in the cache at all..
