### ISSUE TITLE
Observer, custom directory bug?

### ISSUE THREAD

**Issue by huglester** [fuel/orm#69]
Hello,

when I tried using observer in custom directory, I started getting this:

Error: Argument 1 passed to Observer_Queue::after_load() must be an instance of Model, instance of Model_Queue given, called in /var/www/vhosts/vibe/fuel/packages/orm/classes/observer.php on line 23 and defined in /var/www/vhosts/vibe/fuel/app/classes/observer/queue.php on 10

example code here: http://scrp.at/adu
As you can see, simply removing Model from method arguments, solved the problem.
Not sure if this is a bug, just wanted to let you know :)

if I pust this observer with light modifications into the packages/orm dir... they work with "Model " 

Thanks for good TOOL and good luck! :)

**Comment by jschreuder** [comment]
The bug is in your code, you copied everything, removed the namespace, but didn't update the classname to include the namespace. The error is thus completely correct: the model is not an instance of "Model". It is an instance of "Orm\Model" though...

**Comment by huglester** [comment]
Thank you Jelmer!
