### ISSUE TITLE
Observer, after_load() problems...

### ISSUE THREAD

**Issue by huglester** [fuel/orm#70]
Hello,
I'm building some queue system for tasks, to work out with sending mail notifications,
prepairing daily mails based on different data, etc.

I have a working observer: http://scrp.at/adZ
and part of script, which deals pulling data out of mysql and firing the methods:
http://scrp.at/ad0

But somehow (not sure when or why), the observer is not unserializing the data on 'first run' (not sure how to properly name it)
http://d.pr/gw3g - as you can see, I've got an error, email is bad, after debuging, I"ve spotted that this string is unserialiazed...

but later if I run this script once again, queue pasts just nicely (and I also see, that it is unserialized): http://d.pr/5fp9

I'm really not sure how to debug/test it deeper... if there is anything more I can do for debug - just let me know!

Thank you

**Comment by huglester** [comment]
I had played a bit more, have created a method called Str::is_serialized(), so I can check if it's serialized, if so - unserialize to test out things:

http://d.pr/1GyX - as you can see - those 'prepared for queue', and  then you see, that the data it grabs is serialized :( 

but if you take a look at the bottom, you'll see that I have pressed ctrl+c after task #99, then did run oil refine once again....
and you see it added task 100 with success, and the first 'Sending email' had a success, and second - failed

it looks like it pulls two records 'nicely' while the 3rd+ becomes buggy..

No idea, this is insane :(

**Comment by jschreuder** [comment]
These observer methods don't mirror eachother and will get you into trouble: when saving the contents is serialized for the database but not unserialized to work with after that. The solution would be to add an after_save method for unserialization.

Please verify this solves it so the issue can be closed.

**Comment by huglester** [comment]
Hello jschreuder, 

your solution seemed to work. Thank you :)
