### ISSUE TITLE
Include initdb Task in ORM package?

### ISSUE THREAD

**Issue by jondavidjohn** [fuel/orm#72]
This is more an idea, just thought I'd offer my initdb task to be included in the ORM package, as it relies on it, and in my mind would be a fairly good feature for the ORM to include out of the box.

To allow an ORM user not have to even worry about interfacing with the database, just write out your models in php.

https://github.com/jondavidjohn/fuel-initdb

**Comment by jschreuder** [comment]
I like it but I feel it should remain a 3rd party class. Not everything belongs in the official package, that's part of the reason for packages & other ways we allow for easy extension. Once we get our official extension site "Fuel Cells" up and running that'll give better exposure to good extensions like yours.

**Comment by jondavidjohn** [comment]
Yeah, I understand, just thought it _might_ be something you would want to include out of the box for ORM users, can't wait to see this fuel cells site, thanks.
