### ISSUE TITLE
Observer_Validation callables issue

### ISSUE THREAD

**Issue by phil-lavin** [fuel/orm#74]
Observer_Validation won't re-add a callable because of the in_array check on $_generated. This means that, when you are running 2 consecutive save() calls on model instances of the same type, the second is not added as a callable. It is important that the first instance is removed as a callable and the new one added because custom validation rules on a model can reference $this.

Ideally, the Fieldset needs to be reset on each call to the validation observer, rather than recycling the singleton. We tried writing some code to allow you to remove callables but the references to the old callable spread a lot deeper in the Validation object. Perhaps the factory() method on Fieldset should always create a new instance, overwriting the original.

Thanks :)

**Comment by andrewwheal** [comment]
This issue is becoming a real annoyance as it means that you can not have any unique validation rules on Models associated with one-to-many or many-to-many relations

**Comment by jschreuder** [comment]
I've been thinking about this, the only solution I've been able to come up with is to add a 3rd param to the `Validation::run()` method that allows you to add temporary callables. This should also remove the class which you've added from the callable list to prevent double calling on both static & dynamic usage.

**Comment by phil-lavin** [comment]
How's that? Sorry it's a bit of a mess of pull requests into 2 repos. Perhaps discussion is best handled here.

This is the associated pull request: https://github.com/fuel/core/pull/452

Phil

**Comment by jschreuder** [comment]
Not sure why this wasn't closed.
