### ISSUE TITLE
WHERE OR in query array is broken

### ISSUE THREAD

**Issue by kbanman** [fuel/orm#75]
As discussed in IRC:

Trying to produce a query from arrays including an `OR` causes an error:
https://github.com/fuel/orm/blob/1.0%2Fmaster/classes/query.php#L107 is incorrectly parsing the `OR` as a field.

Example code:

```
$options = array(
    'where' => array(
        array('name_first', '=', 'john',
        'or' => array('name_last', '=', 'smith'))
    )
);

$posts = Model_Post::query($options)->get();
```

**Comment by jschreuder** [comment]
Note to self: the referred line matches 'or' but it should only be matched in the `elseif` condition. Check full logic and see if it still makes sense...

**Comment by kbanman** [comment]
Ok, just had another look at this, and my example code is wrong.

This example code runs correctly:

```
$options = array(
    'where' => array(
        array('name_first', '=', 'john'),
        'or' => array('name_last', '=', 'smith'),
    )
);

$posts = Model_Post::query($options)->get();
```

But the following code brings up a mysql error (`Unknown column 't1.or' in 'where clause'`) :

```
$options = array(
    'related' => array(
        'author' => array(
            'where' => array(
                array('name_first', '=', 'john'),
                'or' => array('name_last', '=', 'smith'),
            ),
        ),
    ),
);

$posts = Model_Post::query($options)->get();
```

**Comment by kbanman** [comment]
After some further digging, it seems the problem is actually in [this loop](https://github.com/fuel/orm/blob/1.1%2Fdevelop/classes/query.php#L643).
I think the solution will be to transplant the logic from [here](https://github.com/fuel/orm/blob/1.1%2Fdevelop/classes/query.php#L113) to that loop, but I'll leave that to you.
