### ISSUE TITLE
Cyclic dependencies seem to break sanitisation

### ISSUE THREAD

**Issue by Altreus** [fuel/orm#77]
I think this is related to my database structure but I can't reproduce it without spending time I won't have for a couple of weeks.

On occasion, if I set a view element like this:

```
$v->model = $model;
```

or this:

```
$v->set('model', $model);
```

Then I get

```
ErrorException [ Error ]: Maximum function nesting level of '100' reached, aborting!

PKGPATH/orm/classes/model.php @ line 667

{main}(  )  index.php: 0
Fuel\Core\Request->execute(  )  index.php: 44
call_user_func_array(  )  core/classes/request.php: 379
PartyPlanner\Controller_Party->action_index(  )   core/classes/request.php: 0
Fuel\Core\View::set_global(  ) modules/partyplanner/classes/controller/party.php:41
Fuel\Core\Security::htmlentities(  )  core/classes/security.php: 183
Fuel\Core\Security::htmlentities(  )  core/classes/security.php: 183
Fuel\Core\Security::htmlentities(  )  core/classes/security.php: 183

... 100 times ...

Orm\Model->offsetSet(  ) orm/classes/model.php: 0
Orm\Model->__set(  )   orm/classes/model.php: 1153
PartyPlanner\Model_Account->__get(  ) classes/model/account.php: 0
Orm\Model->__get(  ) modules/partyplanner/classes/model/account.php: 59
```

If I set it with:

```
$v->set('model', $model, false);
```

then it works. This appears to be a side-effect of deserialisation:

```
$model = Session::get('stored_model');
```

I suspect it has something to do with my odd database structure (which is the structure any non-dynamic database engine eventually takes when trying to store data for dynamic code):

```
Party   1---*  Account
     *            1
     |            |
  Guest *----------
```

There is a cyclic relationship, whereby a party has_many Guests, an Account adorns a Guest and therefore belongs_to Guest, and a Party has_one Account, which resolves to the Guest that created it.

The interesting thing is that this structure has been around for a long time but the issue has only just cropped up.

I will spend time investigating when the current project is over, if no one else has :)

**Comment by jschreuder** [comment]
Do you have additional clean methods set other than the default `Security::htmlentities()`? `Security::htmlentities()` keeps track of what has been cleaned already thus it shouldn't be possible that would go into an unending loop. (which I tested at the time with the Orm btw)

**Comment by Altreus** [comment]
No, I haven't done anything non-default.

The loop only seems to happen if I deserialise one of the objects out of the session before assigning it to a view. I could be barking up the wrong tree with the cyclic structure thing but it seems to be the only difference I can see at the moment.

**Comment by jschreuder** [comment]
Deserialization might make an object with the same ID exist more than once in runtime, I doubt however that's  the cause here because even if it exists twice that shouldn't go up to a 100 deep. It's still very strange because (as I mentioned) our own htmlentities keeps track of which objects were encoded already and doesn't do an object a second time.

**Comment by jschreuder** [comment]
As this is an issue with the Core I'm going to refer further discussion on this to https://github.com/fuel/core/issues/450 - I'll submit a fix in a few minutes.
