### ISSUE TITLE
NULL is saved to the database as 0

### ISSUE THREAD

**Issue by lukearmstrong** [fuel/orm#82]
I have a foreign key which can either be NULL, or it can be set as a valid primary key from another table - it cannot be set to 0.

When I load the model from the database, the field is NULL, which it should be.

__event_before_save() also shows the field as NULL.

save() throws an error because the query has been written with `field` = '0'. The field should be in the UPDATE query, as I may need to set things from a valid key back to NULL again, but my problem is why it is set to 0 when it is NULL in the model.

This code used to work until I updated to 1.1-dev and updated the ORM package.

**Comment by lukearmstrong** [comment]
Sorry, forgot to mention I am using MySQL

**Comment by jschreuder** [comment]
I just checked, I have no trouble setting fields to `NULL` in my own code.

**Comment by lukearmstrong** [comment]
Further testing shows that without even touching those fields, they get converted from NULL to FALSE between ORM and the Query Builder, which then resolves to 0.

**Comment by lukearmstrong** [comment]
INSERT error:

Fuel\Core\Database_Exception [ 1452 ]: Cannot add or update a child row: a foreign key constraint fails (`db/products`, CONSTRAINT `FK_products_sub_categories_id` FOREIGN KEY (`sub_category_id`) REFERENCES `sub_categories` (`id`) ON DELETE SET NULL ON UPDATE CASCADE) [ INSERT INTO `products` (`name`, `subtitle`, `description`, `url`, `page_title`, `meta_description`, `meta_keywords`, `sub_category_id`, `collection_id`, `style_id`, `live`, `visibility`, `deleted`, `created_at`, `updated_at`) VALUES ('test', '', '', '', '', '', '', '0', '0', '0', '0', 'ALL', 0, 1315314978, 1315314978)

UPDATE error:

Fuel\Core\Database_Exception [ 1452 ]: Cannot add or update a child row: a foreign key constraint fails (`db/products`, CONSTRAINT `FK_products_collections_id` FOREIGN KEY (`collection_id`) REFERENCES `collections` (`id`) ON DELETE SET NULL ON UPDATE CASCADE) [ UPDATE `products` SET `name` = 'Adam', `subtitle` = '', `description` = '', `url` = '', `page_title` = '', `meta_description` = '', `meta_keywords` = '', `sub_category_id` = '1', `collection_id` = '0', `style_id` = '0', `live` = '1', `visibility` = 'ALL', `deleted` = '0', `created_at` = '1315303410', `updated_at` = 1315315057 WHERE `id` = '37' LIMIT 1 ]

**Comment by lukearmstrong** [comment]
whoops, seems to be a problem with our observer.

will re-open if this does turn out to be a bug in fuel.

**Comment by WanWizard** [comment]
This is a duplicate of issue #83. The returned value false is converted to '0' by the QB.
