### ISSUE TITLE
Observer_Validation problems with null fields

### ISSUE THREAD

**Issue by phil-lavin** [fuel/orm#83]
Observer_Validation runs the validation and, on success, it loops the fields and re-assigns the value into the object from $val->validated().

``` php
foreach ($input as $k => $v)
{
    $obj->{$k} = $val->validated($k);
}
```

The problem with this is that $val->run() is called with the 2nd param as true to allow partial. This means that when the value is null, the loop inside the validation class will continue and not assign to the validated array:

``` php
if ($allow_partial && $value === null)
{
    continue;
}
```

This means that when it does the first loop that I referenced, validated() will return false and false will be put into the object in place of null. This also means that validation will be skipped for required fields whose value is null.

I recall you only changed false to true to the other day to solve the issue I was having with data that was not in POST being required.

@WanWizard @SicoAnimal and I weren't too sure where to go with this one. Thoughts @jschreuder?

**Comment by jschreuder** [comment]
Pff, never think this is easy - it started out as such a nice small observer ;). You're right this is a problem, also it should probably run a full validation on insert and only partial on update. We may need some mods to Validation to ultimately solve this, not sure yet. One solution would be to change the $allow_partial setting in Validation::run() to accept an array of fields to check, then we could still validate null values.

**Comment by jschreuder** [comment]
I didn't get to fully test this and will be away for most of the day tomorrow, could you verify this fix for me?

**Comment by phil-lavin** [comment]
This seems to have fixed the issue we were having. @lukearmstrong @sicoanimal
