### ISSUE TITLE
Validation doesn't run on fields that were not changed.

### ISSUE THREAD

**Issue by lukearmstrong** [fuel/orm#85]
I have a mysql table I have imported a load of data. Some fields are empty.

I created an orm model for the table, and set validation => array('required') on some of the fields. Then I created some CRUD pages.

When creating a new "row", the validation throws this exception: \Orm\ValidationFailed if a required field is empty.

But when editing a "row", the validation doesn't run on fields that were not changed. So as the field was already empty, it doesn't validate the field when I save.

This may not be considered a bug, but certainly had me scratching my head for awhile until the penny dropped.

As a "fix" I am having to set anything that is empty in the database to NULL. Now Fuel sees the field has changed, as it was NULL, and it has been set with an empty string.

**Comment by jschreuder** [comment]
It is indeed not a bug, full validation is only done upon inserts and updates only check the changed values.

EDIT: to clarify a bit more about the logic behind this: Validation is about validating (and possible parsing) user input, unchanged object properties don't contain user-input but instead whatever you put in it for which validation isn't meant.
