### ISSUE TITLE
has_one fails on delete

### ISSUE THREAD

**Issue by joshuarubin** [fuel/orm#88]
If has_one has cascade_delete = false, and the key_to is the primary key of the model_to, then fuel will throw an error because the primary key is being updated.

I don't think this is a very good idea, see the commit comment here for a more detailed explanation:
https://github.com/fuel/orm/commit/9c3c8d982a148ee4bcb51a26afa9ce840bea4cb4#commitcomment-593081

**Comment by jschreuder** [comment]
As I've explained in your line note: the `key_to` in a "has one" relation is the foreign key, which should never be a primary key. In the relation you explained it should have been a "belongs to" in which case the foreign key `users.title_id` would have been reset instead of `titles.id`.
