### ISSUE TITLE
Db::expr doesn't work with SELECT

### ISSUE THREAD

**Issue by dspangenberg** [fuel/orm#89]
<code>
$payments = Model_Payment::query()->select(\Db::expr('SUM(ammount)'))->get();
</code>

Unknown column 't0.SUM(ammount)' in 'field list' [ SELECT `t0`.`SUM(ammount)` AS `t0_c0` FROM `payments` AS `t0` ]

<code>
$payments = Model_Payment::query()->select(\Db::expr('SUM(payments.ammount)'))->get();
</code>

Unknown column 'SUM(payments.ammount)' in 'field list' [ SELECT `SUM(payments`.`ammount)` AS `t0_c0` FROM `payments` AS `t0` ]

**Comment by jschreuder** [comment]
It was never meant to, there are already features in the planned list to deal with this but basicly it also comes down to the fact that some things are better done with SQL/the Query Builder than the Orm.
