### ISSUE TITLE
Messed up Has Many relation after create

### ISSUE THREAD

**Issue by andrewwheal** [fuel/orm#90]
I am doing the following:
1. forging an instance of a model ($vacancy)
2. filling out its properties
3. forging 5 instances of another model and putting these into a has_many relation on $vacancy
4. saving $vacancy

When I then try to access the items of the relation there are only 2 items with the id's 0 and '' (empty string)

Code snippet:

``` php
$vacancy = Model_Vacancy::forge();
$vacancy->quantity = $post['quantity'];
$vacancy->description = $description;

foreach ($questions as $question_str) {
  $question = Model_Question::forge();
  $question->question = $question_str;
  $vacancy->questions[] = $question;
}

var_dump($vacancy);

$vacancy->save();

var_dump($vacancy);
```

The first var_dump() shows 5 questions with id's 0 - 4

The second var_dump() shows 2 questions with id's 0 and '' (empty string)

Will add some debug and see if I can figure out what is happening...

**Comment by jschreuder** [comment]
Does your Model_Question have a primary key?

**Comment by andrewwheal** [comment]
Yes, the default 'id'

**Comment by jschreuder** [comment]
I think I got it, don't have time to fix it/test it though: https://github.com/fuel/orm/blob/1.1%2fdevelop/classes/hasmany.php#L148

It reads: `if ($key != $current_model_id)` but $current_model_id is empty for instances only saved when saving their parent object. I think to bugfix this it'll have to change to:

```
if ($key != ($current_model_id = $model_to->implode_pk($model_to)))
```

With that the $current_model_id should always have the right value.

**Comment by andrewwheal** [comment]
Yep, that fixed it @jschreuder

Will keep working with that change in my version and keep an eye out for anything else it might have affected

**Comment by jschreuder** [comment]
@SicoAnimal next time leave it to me to close, hadn't pushed the fix yet so it was still broken in the repo.

**Comment by andrewwheal** [comment]
Oh, sorry @jschreuder

Closed it as I hadn't found any problems... live and learn
