### ISSUE TITLE
'model_to' => 'modulename::Model_Comment'

### ISSUE THREAD

**Issue by DregondRahl** [fuel/orm#93]
This is probably a dumb idea but just suggesting it, if at all it makes sense, as I have no real understanding of the ORM coding. But would it be possible to have it similar to how config finds by modulename the config file. Maybe similar for ORM then it will load the related module's model only when using related(). I read that lazy loading of relations on a model will be a future feature, but i was wondering if there would be an advantage of using it this way too, so the whole module doesn't need to be loaded if only the model is needed, it would be similar to HMVC requests and such.

``` php
protected static $_has_many = array(
    'comments' => array(
        'key_from' => 'id',
        'model_to' => 'comments::Model_Comment',
        'key_to' => 'post_id',
        'cascade_save' => true,
        'cascade_delete' => false,
    )
);

```

**Comment by WanWizard** [comment]
Loading a module doesn't actually do anything other then making the namespace known, so it doesn't have any overhead. If you would use this syntax, it will have to load the module anyway, otherwise the autoloader wouldn't know where to load the Model_Comment class from...

**Comment by DregondRahl** [comment]
Thanks WanWizard that makes sense, i was thinking that using this way we don't have add:

``` php
\Fuel::add_module('comments');
\Fuel::add_module('users');
\Fuel::add_module('likes');
```

For the controller, when using different modules. The ORM can add the namespace when its used on a related() method when it is lazy loading relations.

**Comment by jschreuder** [comment]
This is not a job for the Orm, either always-load or manual load. The Orm has no business loading packages.
