### ISSUE TITLE
_event_$action does not provide an instance of the model

### ISSUE THREAD

**Issue by ergovschi** [fuel/orm#94]
Observer\Self does not provide an instance of the current model to the called method (_event_before_save(), _event_after_load(), etc. ).
This renders the Observer\Self kinda useless.

Fix:
Change classes/observer/self.php line:21 to

```
call_user_func(array($instance, $method), $instance);
```

**Comment by jschreuder** [comment]
You do realize it's called on the actual object, thus it's incredibly useless to provide the object which is already available as the PHP native `$this` inside your method?
