### ISSUE TITLE
has-many only returns one object

### ISSUE THREAD

**Issue by phil-lavin** [fuel/orm#96]
I don't have time to look into it presently, I have just reverted the upgrade however it caused has_many relationships to only return 1 row rather than multiple.

**Comment by jschreuder** [comment]
Can you please tone down the subject? It is so incredibly useless I almost closed this out of spite.

**Comment by jschreuder** [comment]
Also I'm closing this for too little info if my first attempt doesn't replicate the issue.

**Comment by phil-lavin** [comment]
Urgh. Sorry, this was related to some debug code we left in from debugging the previous issue I reported. All is well. Sorry for getting cranky - deadlines loom.

Phil
