### ISSUE TITLE
Using DB::expr in ORM

### ISSUE THREAD

**Issue by zoe-edwards** [fuel/orm#98]
I would like to be able to use DB::expr in ORM, for example:

```
return Model_Advert::find('first', array(
    'where'    => array(array('start', '<', DB::expr('NOW()')))
));
```

**Comment by jschreuder** [comment]
What version are you using? I think this is fixed in the 1.1-dev branch.

**Comment by zoe-edwards** [comment]
Ah, using 1.0.1; the site’s in production so I’m not sure about upgrading yet. Will test and get back if it doesn’t work.

Cheers.

**Comment by jschreuder** [comment]
It won't work because the relation classes use the newly added `get_real_class()` function, you could try just updating the Query class I don't think that has any dependencies in the core that have been changed.
