### ISSUE TITLE
Problem with limit() and get_one()

### ISSUE THREAD

**Issue by phil-lavin** [fuel/orm#99]
If I do \Model_Subcategory::find()->where('live', 1)->related('category')->where('category.url', $category)->order_by('order', 'ASC')->get(); it produces this:

``` sql
SELECT `t0`.`id` AS `t0_c0`,
       `t0`.`category_id` AS `t0_c1`,
       `t0`.`name` AS `t0_c2`,
       `t0`.`url` AS `t0_c3`,
       `t0`.`page_title` AS `t0_c4`,
       `t0`.`meta_description` AS `t0_c5`,
       `t0`.`meta_keywords` AS `t0_c6`,
       `t0`.`order` AS `t0_c7`,
       `t0`.`live` AS `t0_c8`,
       `t0`.`deleted` AS `t0_c9`,
       `t0`.`created_at` AS `t0_c10`,
       `t0`.`updated_at` AS `t0_c11`,
       `t1`.`id` AS `t1_c0`,
       `t1`.`name` AS `t1_c1`,
       `t1`.`url` AS `t1_c2`,
       `t1`.`page_title` AS `t1_c3`,
       `t1`.`meta_description` AS `t1_c4`,
       `t1`.`meta_keywords` AS `t1_c5`,
       `t1`.`order` AS `t1_c6`,
       `t1`.`live` AS `t1_c7`,
       `t1`.`deleted` AS `t1_c8`,
       `t1`.`created_at` AS `t1_c9`,
       `t1`.`updated_at` AS `t1_c10`
FROM `subcategories` AS `t0`
LEFT JOIN `categories` AS `t1` ON (`t0`.`category_id` = `t1`.`id`)
WHERE `t0`.`live` = 1
  AND `t1`.`url` = 'women'
ORDER BY `t0`.`order` ASC
```

If I do \Model_Subcategory::find()->where('live', 1)->related('category')->where('category.url', $category)->order_by('order', 'ASC')->get_one(); it produces this:

``` sql
SELECT `t0`.`id` AS `t0_c0`,
       `t0`.`category_id` AS `t0_c1`,
       `t0`.`name` AS `t0_c2`,
       `t0`.`url` AS `t0_c3`,
       `t0`.`page_title` AS `t0_c4`,
       `t0`.`meta_description` AS `t0_c5`,
       `t0`.`meta_keywords` AS `t0_c6`,
       `t0`.`order` AS `t0_c7`,
       `t0`.`live` AS `t0_c8`,
       `t0`.`deleted` AS `t0_c9`,
       `t0`.`created_at` AS `t0_c10`,
       `t0`.`updated_at` AS `t0_c11`,
       `t1`.`id` AS `t1_c0`,
       `t1`.`name` AS `t1_c1`,
       `t1`.`url` AS `t1_c2`,
       `t1`.`page_title` AS `t1_c3`,
       `t1`.`meta_description` AS `t1_c4`,
       `t1`.`meta_keywords` AS `t1_c5`,
       `t1`.`order` AS `t1_c6`,
       `t1`.`live` AS `t1_c7`,
       `t1`.`deleted` AS `t1_c8`,
       `t1`.`created_at` AS `t1_c9`,
       `t1`.`updated_at` AS `t1_c10`
FROM
  (SELECT `t0`.`id`,
          `t0`.`category_id`,
          `t0`.`name`,
          `t0`.`url`,
          `t0`.`page_title`,
          `t0`.`meta_description`,
          `t0`.`meta_keywords`,
          `t0`.`order`,
          `t0`.`live`,
          `t0`.`deleted`,
          `t0`.`created_at`,
          `t0`.`updated_at`
   FROM `subcategories` AS `t0`
   WHERE `t0`.`live` = 1
   ORDER BY `t0`.`order` ASC LIMIT 1) AS `t0`
LEFT JOIN `categories` AS `t1` ON (`t0`.`category_id` = `t1`.`id`)
WHERE `t1`.`url` = 'women'
```

It seems that putting a limit on the query creates a subselect and limits that, rather than what I would expect to happen - which is that it puts the limit on the end of the existing query. Expected behaviour is that the result of a get_one() is the same as doing a reset() on the result of a get().

**Comment by jschreuder** [comment]
No it isn't, if you do a reset() on the result of a get() the Orm would need to fetch and parse all other objects as well which adds potentially massive unneeded overhead.

**Comment by phil-lavin** [comment]
I wasn't suggesting that is what it should do... I was simply saying that the results should be the same. It seems that the limit is being put in the wrong place.

**Comment by jschreuder** [comment]
It's not, imagine what would happen if you were joining 5 categories on your subcategory and `LIMIT 1` would be placed at the end of this query instead of put into a subquery.

**Comment by phil-lavin** [comment]
I'm not sure I understand the point of get_one() then. In this case, it returns no result (null) whereas get() returns an array of 2 results. What is the purpose of get_one()?

**Comment by jschreuder** [comment]
The problem is that in cases like this there is no perfect solution:
- You can just use get() and do a reset() once its done, in which case you might have to parse 10000 objects to get 1.
- You can put `LIMIT` at the end, in which case you can never get all relations for to-many relations but only the first one of each
- You can use a subquery with LIMIT (which is what our Orm does), but that has the limitation that you can get nothing back if you put conditions on the joined table outside the JOIN ON

There's no perfect solution.

**Comment by Altreus** [comment]
Unless the query builder accepted Query objects as subqueries, and then any limiting, ordering or grouping would be done to the outer Query in all cases. Then all the helper functions would create Query objects in the background and assemble them as subqueries, but if you wanted the current (inconsistent) behaviour you would have to construct your own subquery.

Bagsy not it

**Comment by jschreuder** [comment]
> Unless the query builder accepted Query objects as subqueries

It does, but I'm not sure why this discussion belongs here?

> Then all the helper functions would create Query objects in the background and assemble them as subqueries, but if you wanted the current (inconsistent) behaviour you would have to construct your own subquery.

Could you give examples of what you mean? Because I don't get how you would solve it. I'm all ears for a better solution, I'm just not open for a different solution that has more downsides IMO.

**Comment by phil-lavin** [comment]
I see your point but it is unexpected behaviour that it should return no results when get() returns results. Could it detect if it's going to fail and fall back to using the slow reset() method if it will? I think it's better that it should be slow than broken. At least if it's slow, people can bypass ORM and make an optimized query. 

It could also break it down into multiple queries to avoid the overhead of unnecessarily creating objects.

**Comment by jschreuder** [comment]
Write up a solution and I'm all ears. I don't think that "detect if it's going wrong" is actually possible though without adding significant overhead, and a fallback to something that might potentially fetch 10000 objects when you need 1 is an institutionalized bug.

Breaking it up into multiple queries is something that has been in the issue tracker for a while, I intend to add support for fetching relations through a where-in query rather than a normal join. That wouldn't solve your issue however, you actually need the join for the correct output.

**Comment by phil-lavin** [comment]
Re-open the issue and I'll have a look into a possible solution for breaking up the query when I get a little more time.
